### ISSUE TITLE
Fork Hashicorp Vault

### ISSUE THREAD

**Issue by naphelps** [openbao/openbao#1]
Fork the current and near future Vault source to this repository. Must include the current and future source for the 1.14.x stream of Vault changes.

More requirements to come.

**Comment by Anutrix** [comment]
Any info on when the first merge to `main` branch will happen? It seems all code is in `development` branch.

**Comment by naphelps** [comment]
That will happen once we get closer to having some form of release candidate.

**Comment by victor-bolivar** [comment]
> @Anutrix That will happen once we get closer to having some form of release candidate.

Hi @Anutrix 

I hope you're doing well. I appreciate the hard work that's gone into the development branch so far, I understand that it's a complex process. I was wondering if you could share a bit more about the timeline for the release candidate. Knowing more about when we might expect a release candidate would help my team migrate from the old Hashicorp's Vault and adopt OpenBao instead.

Thanks so much for your time and effort on this.

**Comment by naphelps** [comment]
@victor-bolivar I recommend registering and attending the development community calls on Thursdays @ 11:00AM Eastern. You can register here: https://lists.lfedge.org/g/openbao

We do not have a formal timetable as of today for any future release candidate. The community is in ongoing discussion as to what will be included in the first release of the project, as well as how certain features will be organized and hosted with this Git organization.
