### ISSUE TITLE
Fork - Swap documentation website styling for OpenBao

### ISSUE THREAD

**Issue by cipherboy** [openbao/openbao#118]
In the documentation under `/website`, we pull in a lot of HashiCorp branding assets & space. While we've done work on the content of the docs, we've not yet figured out how to build the docs for hosting and how to decouple ourselves from the HashiCorp website structure present there.

Ideally, I believe in the past community calls, we've talked about hosting on GitHub, so we probably require some sort of translation pipeline from Vercel documentation to GH Pages.

**Comment by cipherboy** [comment]
@JanMa I think this is fixed as part of #156? :-)

**Comment by JanMa** [comment]
I guess it is 😄 👍
