### ISSUE TITLE
Fork - Remove references to Enterprise from user-visible code base

### ISSUE THREAD

**Issue by cipherboy** [openbao/openbao#121]
Searching for `Enterprise` in the Go code base makes numerous references. We should probably audit and trim these down as much as possible, especially where e.g., they are returned in user-facing strings.

This likely means removing references to managed keys presently (from Transit and PKI) as that code is not present in OpenBao. 

#126 applied to the CLI, but I think we're probably better off keeping it, IMO.

**Comment by Gabrielopesantos** [comment]
Hey,
I would like to work on this. If none is working on it yet, feel free to assign it to me.
