### ISSUE TITLE
Fork - Remove references to Vault Enterprise in the UI

### ISSUE THREAD

**Issue by cipherboy** [openbao/openbao#129]
This task is to remove reference to Vault Enterprise from the UI. This is likely a more invasive change, as the UI is presently set up to handle both OSS and Enterprise plugins & features. However, much of the Enterprise functionality is not tagged explicitly, so it might be hard to do (suggestion: remove one feature at a time).

**Comment by testn** [comment]
What do we need to do? I can help on this

**Comment by cipherboy** [comment]
\o hey @testn! Thank you :D 

I think #154 is the best place to start. I had started removing things but right now `yarn run oss:test` fails with no clear error message and with a lot fewer (30 vs 1000+) tests than pre-fork. I'm not entirely sure what I've broken, but you can look through `git log ui/` to get a sense of that.

**Comment by michael-sparrow** [comment]
Is it expected to get this bug fixed till the end of this year?

**Comment by cipherboy** [comment]
@michael-sparrow #739 will remain open but I think this one can likely close. I'll verify it when I get time.

**Comment by cipherboy** [comment]
This looks to be complete. Thanks @bozzo, @arminfelder, and @JanMa and whomever else I might've forgotten to thank!

**Comment by JanMa** [comment]
@cipherboy there's still some enterprise code left in the UI which i am currently cleaning up
