### ISSUE TITLE
docs: recreate images and diagrams

### ISSUE THREAD

**Issue by JanMa** [openbao/openbao#149]
Many images and diagrams in the docs show the Vault logo and we need to recreate those with OpenBao branding.
I am currently unsure if we should recreate/edit the images or if it might be even better to replace them with [Mermaid Diagrams](https://mermaid.js.org/) which are natively supported in the Markdown engine we use to render the docs.

**Comment by joewxboy** [comment]
I'm a big fan of diagrams as code, but state of the art a year ago had limitations on spacing and unpredictable layout. We should probably pick a few samples and see if Mermaid can achieve the spirit of the desired output. Otherwise I'd recommend draw.io, and also version the draw.io sources.

**Comment by David-Langan** [comment]
@naphelps - making a comment here so that you can assign this to me.
