### ISSUE TITLE
OpenAPI Generated Docs

### ISSUE THREAD

**Issue by cipherboy** [openbao/openbao#15]
Currently API docs are hand-maintained: https://github.com/openbao/openbao/tree/development/website/content/api-docs

This has lead to a divergence between them and the in-code docs at various points of time; while OpenBao uses a custom framework, it has the ability to generate an OpenAPI schema and thus should have the ability to generate OpenAPI docs, which would decrease the burden of accepting changes and increase maintainability of our documentation. 

This needs to be done carefully as the hand-written docs and the OpenAPI docs will likely differ, so we'll likely want to go plugin-by-plugin and manually review and merge back any useful changes.

**Comment by JanMa** [comment]
I took a closer look into this, and as far as I can see a lot of the prerequisites are already in place. Using the [gen_openapi.sh}(https://github.com/openbao/openbao/blob/development/scripts/gen_openapi.sh) script and [openapi generator](https://openapi-generator.tech/) we can already produce some pretty solid API docs. 

What's still left to do is to adjust the default template of the document generator we choose to use with the `openapi generator` so it fits into  the upcoming openbao website

**Comment by cipherboy** [comment]
I'm going to go ahead and close this as it is not close to being achievable in the short-term. The OpenAPI schemas have many gaps that will need to be addressed first.
