### ISSUE TITLE
Extensible seal mechanism

### ISSUE THREAD

**Issue by bnevis-i** [openbao/openbao#16]
I could be mistaken, but I do not think that the current seal mechanism is extensible.  It would be useful, in IoT scenarios for example, to be able to support hardware seals that aren't enterprise HSM's (for example, a TPM 2.0 seal).

**Comment by joewxboy** [comment]
@bnevis-i This sounds like an interesting and potentially valuable feature, but also one that will take a non-trivial amount of work to implement.  If so, do we have a "Sponsor User" in mind who is looking to use this who can help inform requirements and facilitate acceptance testing?

**Comment by jbutlerdev** [comment]
I can't really meet the needs of what @joewxboy is looking for, however I'm definitely interested in helping make this happen. This is a feature I've been looking for in the past.

**Comment by cipherboy** [comment]
I think these are two separate discussion topics, do you mind splitting them into two?

**Comment by cipherboy** [comment]
Closing as more discussion has gone on in #300. PKCS#11 support has been proposed in go-kms-wrapping if you'd like to try it out!

**Comment by chester89** [comment]
I'm interested in having unseal through s3 bucket. Cloud options are great, but for testing on your laptop it's a bit complicated
