### ISSUE TITLE
Remove All BSL 1.1 and BUSL 1.1 Source

### ISSUE THREAD

**Issue by naphelps** [openbao/openbao#164]
All BSL 1.1 and BUSL 1.1 Licensed source must be removed from the repository prior to the project's formal acceptance into the Linux Foundation.

- [ ] https://github.com/openbao/openbao/blob/d6a36ee21ccbdbf0e262ffa5a61044e61591f759/builtin/logical/transit/path_export_test.go#L2
- [ ] https://github.com/openbao/openbao/blob/d6a36ee21ccbdbf0e262ffa5a61044e61591f759/command/operator_raft_snapshot_inspect.go#L2
- [ ] https://github.com/openbao/openbao/blob/d6a36ee21ccbdbf0e262ffa5a61044e61591f759/command/operator_raft_snapshot_inspect_test.go#L2
- [x] https://github.com/openbao/openbao/blob/d6a36ee21ccbdbf0e262ffa5a61044e61591f759/helper/testhelpers/consul/cluster_storage.go#L2
- [ ] https://github.com/openbao/openbao/blob/d6a36ee21ccbdbf0e262ffa5a61044e61591f759/ui/app/helpers/decode-uri.js#L3
- [ ] https://github.com/openbao/openbao/blob/d6a36ee21ccbdbf0e262ffa5a61044e61591f759/ui/app/styles/utils/swagger.scss#L3
- [ ] https://github.com/openbao/openbao/blob/d6a36ee21ccbdbf0e262ffa5a61044e61591f759/ui/app/templates/vault/cluster/policies/error.hbs#L3
- [ ] https://github.com/openbao/openbao/blob/d6a36ee21ccbdbf0e262ffa5a61044e61591f759/ui/lib/open-api-explorer/addon/components/swagger-ui.js#L3
- [ ] https://github.com/openbao/openbao/blob/d6a36ee21ccbdbf0e262ffa5a61044e61591f759/ui/lib/open-api-explorer/addon/templates/components/swagger-ui.hbs#L3
- [ ] https://github.com/openbao/openbao/blob/d6a36ee21ccbdbf0e262ffa5a61044e61591f759/ui/lib/open-api-explorer/addon/routes/index.js#L3
- [ ] https://github.com/openbao/openbao/blob/d6a36ee21ccbdbf0e262ffa5a61044e61591f759/ui/lib/pki/addon/components/page/pki-issuer-list.ts#L3
- [ ] https://github.com/openbao/openbao/blob/d6a36ee21ccbdbf0e262ffa5a61044e61591f759/ui/lib/pki/addon/components/page/pki-key-list.ts#L3
- [ ] https://github.com/openbao/openbao/blob/d6a36ee21ccbdbf0e262ffa5a61044e61591f759/ui/tests/acceptance/enterprise-replication-unsupported-test.js#L3

**Comment by cipherboy** [comment]
To remove [openbao/helper/testhelpers/consul/cluster_storage.go](https://github.com/openbao/openbao/blob/d6a36ee21ccbdbf0e262ffa5a61044e61591f759/helper/testhelpers/consul/cluster_storage.go#L2) requires us to remove Consul service registration. As it is not a BUSL licensed integration, I think this falls in the spirit of #64. Though, at some point someone might want this functionality added back, so we could consider making service registration pluggable as well.

**Comment by JanMa** [comment]
Looks like this is offending commit: https://github.com/openbao/openbao/commit/ed85e15d841c494122e9a3d39d920d636d2f7899
Maybe it's already enough to just revert it
