### ISSUE TITLE
SSH Secrets Engine: Identity templating for `default_extensions`

### ISSUE THREAD

**Issue by radek-sprta** [openbao/openbao#176]
**Is your feature request related to a problem? Please describe.**
I want to use SSH Secrets Engine to provision ephemeral SSH certs for accessing Github.com. Github.com uses the `login@github.com` extension to indicate the Github user. Just adding `login@github.com` to `allowed_extensions` would let user impersonate anyone from the organization.

**Describe the solution you'd like**
Enable identity templates in `default_extensions` field, so we could use something along the lines of:
```
"default_extensions": {
  "login@github.com": "{{ identity.entity.aliases.<mount_accessor>.name }}"
}
```

**Describe alternatives you've considered**
- Using identity templates for `allowed_parameters` in policy: not supported either
- Use terraform templates to generate a role for each user: impractical due to the number of user

**Comment by cipherboy** [comment]
@radek-sprta happy to take such a PR if you're willing! :-) 

I think the tricky thing is that because this relies on Go's templating, there's a few sharp edges that can't be easily solved, but it ultimately affects everything that uses templating equivalently, so I see no (short-term) reason to not add more such usages.

**Comment by cipherboy** [comment]
As described in https://github.com/hashicorp/vault/issues/25783, this is just a docs change -> https://github.com/openbao/openbao/pull/219

**Comment by radek-sprta** [comment]
Yep, when I started digging in the code it turned it's already implemented, just undocumented.
