### ISSUE TITLE
Contact the Project

### ISSUE THREAD

**Issue by alrs** [openbao/openbao#19]
Hi.

I'm a former "Core Contributor" to Hashicorp Vault across several years, and more recently a contributor to Opentofu.

I'm looking at some of the difficulties with the circular imports between `github.com/hashicorp/vault` and `github.com/hashicorp/vault-plugin-secrets-kv`.

I also have some ideas about bringing all of the plugins into this repo itself.

Is there a mailing list or IRC channel where I can communicate with this project?

**Comment by cipherboy** [comment]
\o Hello @alrs, good to have you :-)

We have a mailing list available at the Linux Foundation's Edge project (the host for this fork): https://lists.lfedge.org/g/openbao -- and a Matrix chat room available under the same: https://chat.lfx.linuxfoundation.org/ (look for rooms with "openbao" in the title). 

Always happy to take ideas, here as issues or elsewhere!

**Comment by cipherboy** [comment]
Going to go ahead and close this :-) 

We've put contact details:

- On the organization overview: https://github.com/openbao#contact
- In the README: https://github.com/openbao/openbao?tab=readme-ov-file#openbao
- On the website: https://openbao.org/docs/contributing/

...and probably more places I'm missing.

If anyone has additional places this should be, please let us know!
