### ISSUE TITLE
Add Merge Queue Support To workflows

### ISSUE THREAD

**Issue by naphelps** [openbao/openbao#225]
With the sometimes high volume of PRs that are created and merged we run into the problem of having to either ask individual authors/contributors to step-wise update rebase their PRs as they are merged, or a maintainer has to rebase the PR themselves causing the commit signing to become unverified. Merge queue can help with this problem, but the existing workflows need to be updated to support the queues.

The DCO bot does not currently support merge queues and a dummy workflow has to be used to force the check to pass. PRs are required to pass the DCO check prior to being added to the queue. https://github.com/dcoapp/app/issues/199

**Comment by cipherboy** [comment]
Hmm @naphelps I'm confused why we're requiring PRs to be rebased prior to merge? Unless as a maintainer you manually push the branch to `main`, clicking the `rebase and merge` button on the GH UI will never give a GPG signed commit and thus will always be marked unverified (see link I sent a while back on Matrix). I don't think merge queues with rebasing will solve this either. 

My 2c. but we could perhaps just merge without requiring up-to-date PRs unless we know there's dependencies between PRs we want to make sure are tested? 

Rather, I think this is conflating two things: up to date for verification (won't work) and merge queues to handle volume. The latter is, on its own, a good idea, but won't solve the former.

**Comment by naphelps** [comment]
@cipherboy Ah, thanks for clarifying. I am hoping it helps with PR merge volume and it also seems to automatically update the successive PRs in the queue as it merges along. Just a builtin benefit. Keeping the PRs update does try to left shift file conflicts and dependencies. It can also help if check failures have more than one contributing issue. Sure we merged in a fix in a different prior PR, but this one is still failing even with the fix from the prior merge. It has captured depend-bot update issues already.
