### ISSUE TITLE
First release

### ISSUE THREAD

**Issue by willifehler** [openbao/openbao#231]
Hi there,

is there any roadmap about a first release of OpenBao?

Cheers - Willi

**Comment by JanMa** [comment]
Hey @willifehler,
we're tracking the progress towards an Alpha and GA release in this repo's [Milestones](https://github.com/openbao/openbao/milestones). As you can see there's not much left for Alpha and if I am not mistaken we're trying to release that end of March/early April. @naphelps can maybe give you more details on the specific timeline

**Comment by naphelps** [comment]
Hello @willifehler,

They community is working hard to try and get the Alpha release out by the end of this week. GA does not have an ETA at this time.

**Comment by naphelps** [comment]
@willifehler Alpha [released](https://github.com/openbao/openbao/releases/tag/v2.0.0-alpha20240329)
