### ISSUE TITLE
Unable to import api / sdk go modules

### ISSUE THREAD

**Issue by ollevche** [openbao/openbao#234]
Hey there!

**Describe the bug**
Running `go get github.com/openbao/openbao/api` results in the following error:

> go: github.com/openbao/openbao/api@upgrade (v1.11.0) requires github.com/openbao/openbao/api@v1.11.0: parsing go.mod:
>         module declares its path as: github.com/hashicorp/vault/api
>                 but was required as: github.com/openbao/openbao/api

**To Reproduce**
1. Init a go module: `go mod init example.test`
2. Run `go get github.com/openbao/openbao/api`
3. See error

**Expected behavior**
OpenBao API go module has been added to project's go.mod as a dependency for further use.

**Environment:**
Clean go module.

**Additional context**
It's possible that Go module proxy server cached the old version of OpenBao API's go.mod (with `github.com/hashicorp/vault/api` specified). It can be resolved by publishing a new go mod version.

**Comment by ollevche** [comment]
To ensure this is a cache problem, you can disable proxy by updating `GOPROXY` via the command: `go env -w GOPROXY=direct`. After that, it imports successfully.

**Comment by cipherboy** [comment]
@ollevche yes, sadly this is a cache issue. Is why I want @naphelps to tag the next alpha as above the past releases. 

When forking, all tags were pushed over and subsequently tagged prior to removal, which has caused issues as we've not yet released. I think perhaps you can do what I did in https://github.com/cipherboy/devbao and pin to a hash in the interim.

**Comment by ollevche** [comment]
thanks for the reply @cipherboy!

Bypassing the go proxy worked for me, but I believe CI could fail later: `GOPROXY="direct" go get github.com/openbao/openbao/api`.

Ideally, you would want to retract older versions, yes. But I think it's fine to simply publish a new one.

BTW when do you plan to release? I'm working on OpenTofu <> OpenBao integration (https://github.com/opentofu/opentofu/issues/1174) and this issue could affect our build process so that's why I'm curious.

**Comment by nerijus** [comment]
Please see https://github.com/openbao/openbao/issues/231#issuecomment-2018939620 about the release.

**Comment by ollevche** [comment]
@nerijus thanks!

**Comment by naphelps** [comment]
@cipherboy I was going to tag the release `v2.20240329.0-alpha`. I am taking other suggestions as well.

**Comment by cipherboy** [comment]
@naphelps 2>1, so that works for me!

**Comment by naphelps** [comment]
@ollevche I have hacked together a stop gap for today. I retagged most of the modules in OpenBao so you should be able to pull our changes. Most modules in openbao are now tagged either `v1.1.0-development20240408` or `v2.1.0-development20240408`.

api: `github.com/openbao/openbao/api@v1.100.0-development20240408`
sdk: `github.com/openbao/openbao/sdk@v1.100.0-development20240408`

going forward we will likely have to go through and increment the major versions of the modules (v0 => v2, v1 => v2, and v2 => v3) to reset the version history and completely remove the prior tags.

**Comment by ollevche** [comment]
@naphelps got you, thanks for the update!

**Comment by cipherboy** [comment]
@ollevche I think https://github.com/opentofu/opentofu/pull/1436 was merged, are we good to close this one? We're slated to cut GA in a couple of weeks and with the 2.0.0 version number, should definitely be surpassing previous tags.

**Comment by ollevche** [comment]
Yep, `go get ...` succeeds so we are good to close. Thanks!
