### ISSUE TITLE
Add support for homebrew installation

### ISSUE THREAD

**Issue by remyleone** [openbao/openbao#24]

**Comment by wayneeseguin** [comment]
https://github.com/Homebrew/homebrew-core/blob/master/Formula/o/openbao.rb

I successfully installed `brew install openbao` on my mac, it installs from the tag that is 2.0.1:
```
bao --version
OpenBao v2.0.0-HEAD ('88383dece6b4ff1b3b242280a54aeabef8101495'), built 2024-09-03T21:19:36Z
```

**Comment by cipherboy** [comment]
Thanks! I'll go ahead and close this
