### ISSUE TITLE
Fix Dependency Vulnerabilities For Alpha Release

### ISSUE THREAD

**Issue by naphelps** [openbao/openbao#240]
- github.com/jackc/pgproto3/v2@v2.3.2 -> 2.3.3
- github.com/jackc/pgx/v4@v4.18.1 -> 4.18.2
- github.com/go-jose/go-jose/v3@v3.0.1 -> 3.0.3

**Comment by cipherboy** [comment]
I have a local branch for this, but I was out of town so I haven't had time to push it.
