### ISSUE TITLE
Unavailable OpenBao documentation website

### ISSUE THREAD

**Issue by ollevche** [openbao/openbao#262]
Hey there!

[The link](https://openbao.github.io/openbao/) mentioned in [the website readme](https://github.com/openbao/openbao/tree/main/website) doesn't work. Also, website [deployment fails](https://github.com/openbao/openbao/actions/runs/8508471460/job/23302086697) due to misconfigured GH pages.

I just want to be up to date with the website going live. Any plans for this?

**Comment by cipherboy** [comment]
\o Hello @ollevche -- we're waiting on a LF ticket to transfer ownership of the `openbao.io` domain to us; once this is done, all of the links will be updated. :-) 

In the mean time, you can browse either @JanMa's [mirror](https://janma.github.io/openbao/) or the in-tree [source docs](https://github.com/openbao/openbao/tree/main/website).

**Comment by ollevche** [comment]
Thanks for the details @cipherboy!

**Comment by JanMa** [comment]
@ollevche the Website is now available at openbao.org

**Comment by ollevche** [comment]
@JanMa thanks for the update!
