### ISSUE TITLE
Compare public keys of incoming client certificates with trusted leaf certs

### ISSUE THREAD

**Issue by JanMa** [openbao/openbao#265]
To prevent the usage of forged client certificates with the same serial number which don't have a matching public key.
This has been fixed in Vault 1.14.10 and we should fix it as well.

**Comment by cipherboy** [comment]
This one should be fixed in 3300aa171fa983a47cb5f12e9287f60fd2891ff7.

**Comment by JanMa** [comment]
Well that was easy :-)
