### ISSUE TITLE
Leftover: change from /etc/vault.d/ to /etc/openbao not fully done in .release/linux/package/usr/lib/systemd/system/openbao.service

### ISSUE THREAD

**Issue by johanneskastl** [openbao/openbao#274]
The systemd service package still looks for its environment file in `/etc/openbao.d/`, while everything else is in `/etc/openbao/` (without the `.d`)

https://github.com/openbao/openbao/blob/a3e93c860dc58e06cab540066be8f15dc93be8df/.release/linux/package/usr/lib/systemd/system/openbao.service#L12

For comparison:
https://github.com/openbao/openbao/blob/a3e93c860dc58e06cab540066be8f15dc93be8df/.release/linux/package/usr/lib/systemd/system/openbao.service#L6
https://github.com/openbao/openbao/blob/a3e93c860dc58e06cab540066be8f15dc93be8df/.release/linux/package/usr/lib/systemd/system/openbao.service#L23

**Comment by cipherboy** [comment]
Thanks @johanneskastl! I've opened #275 to fix this.
