### ISSUE TITLE
FAQ section on the website has old info about forked version

### ISSUE THREAD

**Issue by tsaarni** [openbao/openbao#282]
The FAQ section on the [website](https://openbao.org/) mentions

https://github.com/openbao/openbao/blob/5a1d104da6cf5c9c263c5a11ce6cf1ed4a6f629b/website/src/components/FAQSection/index.tsx#L37-L47

This info is not accurate anymore. 

The last MPL licensed version was v1.14.8. Later versions, including branch [v1.14.x](https://github.com/hashicorp/vault/tree/release/1.14.x) is BUSL licensed.

**Comment by naphelps** [comment]
OpenBao is actually based on an unreleased version of 1.14.9 https://github.com/hashicorp/vault/commit/8993802145833ab01d49c6070d787a9eccb81546, prior to the license change.

**Comment by tsaarni** [comment]
Ah, got it!  [`8993802`](https://github.com/hashicorp/vault/commit/8993802145833ab01d49c6070d787a9eccb81546) was the very last commit before the license change [`48ab1ea`](https://github.com/hashicorp/vault/commit/48ab1eae0894700697d6a705db8fe4eaf7251ad1) - 16 commits after v1.14.8 and 45 commits before v1.14.9.

I wonder if describing it as unreleased v1.14.9 can cause some unnecessary confusion? 

Maybe it could say something like "_based on a commit after v1.14.8 release, before the license change_"... Maybe I'm splitting hairs. :)
