### ISSUE TITLE
Make gofumpt required gating test

### ISSUE THREAD

**Issue by cipherboy** [openbao/openbao#29]
As noted in #28 and current project config, upstream's preference was not to strictly require formatting to succeed, but make it an optional job. IMO it is better to enforce this, since it is project-wide and Go has good community integration for formatters.

See e.g. https://github.com/openbao/openbao/blob/development/Makefile#L248-L249 for make invocation

This will help ensure consistency in PRs and avoid unnecessary follow-ups fixing formatting.

**Comment by cipherboy** [comment]
Here's a link to the test: https://github.com/openbao/openbao/blob/development/.github/workflows/code-checker.yml#L47-L63 

@naphelps @joewxboy do you know if we can make this required? I can see it being run: https://github.com/openbao/openbao/actions/runs/7296386469/job/19884137166?pr=30

**Comment by naphelps** [comment]
Format is now a required workflow gating PRs
