### ISSUE TITLE
No docs on how to install from a package manager

### ISSUE THREAD

**Issue by maulinglawns** [openbao/openbao#305]
**Describe the bug**
No information about repository setup available in:
https://openbao.org/docs/install/#package-manager

**To Reproduce**
When clicking: https://openbao.org/tutorials/getting-started/getting-started-install/
We get a 404

**Expected behavior**
Information on which repository to add.

**Comment by cipherboy** [comment]
I think #151 was tracking the work to create our own tutorials. At least from my search:

```
[cipherboy@x1c docs]$ gif '/tutorials/' | wc -l
112
```

It looks like there's lots of references still to these tutorials, so in the mean time, I'd probably suggest removing them. If anyone's up for it, happy to let them! 

I think Jan is working on a better download page in #302 if anyone wants to check it out :-)

**Comment by maulinglawns** [comment]
> I think #151 was tracking the work to create our own tutorials. At least from my search:
> 
> ```
> [cipherboy@x1c docs]$ gif '/tutorials/' | wc -l
> 112
> ```
> 
> It looks like there's lots of references still to these tutorials, so in the mean time, I'd probably suggest removing them. If anyone's up for it, happy to let them!
> 
> I think Jan is working on a better download page in #302 if anyone wants to check it out :-)

Thank you for the feedback @cipherboy

**Comment by JanMa** [comment]
For the time being we also have no package repository. You can download the matching packages for your OS and architecture directly from our release assets and install them manually

**Comment by maulinglawns** [comment]
> For the time being we also have no package repository. You can download the matching packages for your OS and architecture directly from our release assets and install them manually

Thanks for the reply, much appreciated. By "relase assets", do you mean downloading from here?
https://github.com/openbao/openbao/releases/tag/v2.0.0-alpha20240329

**Comment by cipherboy** [comment]
@maulinglawns Yes, this is correct.

**Comment by maulinglawns** [comment]
> @maulinglawns Yes, this is correct.

Thank you! :bowing_man:
