### ISSUE TITLE
Changelog process - enforce GH workflow

### ISSUE THREAD

**Issue by cipherboy** [openbao/openbao#31]
Currently the changelog process uses [`go-changelog`](https://github.com/hashicorp/go-changelog) for generation. 

It seems like some changelog entries were removed (which IMO, is good as we don't want to maintain it retroactively for prior upstream versions) -- but we likely [want to remove the rest](https://github.com/openbao/openbao/tree/development/changelog) which snuck in. 

In particular, changelog entries are numbered off of PR numbers (and the [README](https://github.com/openbao/openbao/tree/development/changelog#changelog) is generally helpful), so we'll have a ways to go before they'll conflict :-) 

There should be a label ([`pr/no-changelog`](https://github.com/openbao/openbao/blob/development/.github/workflows/changelog-checker.yml)) which avoids the checker in the GH action; it might be nice to make this a required workflow. 

Are there any thoughts on the existing process (doc'd in that README)? Should we choose something else or is this generally amenable to everyone?

**Comment by joewxboy** [comment]
Thanks, @cipherboy .  I need to look at this.

**Comment by cipherboy** [comment]
#70 should remove the unnecessary changelog entries.
