### ISSUE TITLE
Bind tokens to an IP address on issuance 

### ISSUE THREAD

**Issue by thequailman** [openbao/openbao#32]
It would be nice if OpenBao had a configurable token policy to bind a token to the generator's source IP on issuance.  This would help limit token leakage damage, and force roaming clients (like employees or contractors) to reauthenticate if they switch networks.

OpenBao can currently use CIDR ranges to restrict token issuance, but I'd like to see this applied during usage too: a token can only be used from the IP it was issued to.

I think this setting could be added to the general token policies as a bool, maybe `token_bind_source_ip`.

**Comment by cipherboy** [comment]
@thequailman This one should be possible if you're interested in providing a PR. The on-disk definition of the token policy will need to change, as will many of the auth plugins to support this new policy boolean... I _think_, perhaps, we can get away with reusing `tokenutil.TokenParams.TokenBoundCIDRs`, setting the value at token creation time to the actual request source IP address. This gets passed via the adjacent `PopulateTokenAuth` to the auth entry, which should prevent usage from a different IP address. 

Some effort will probably be necessary to handle `X-forwarded-for`, which is already partially supported-ish (e.g., cert auth lacks it), but that can be a separate issue/PR. 

I think this info on the request should be sufficient to allow the backend plugin to decide the source IP without needing to modify Core to do it:

```sdk
    // Headers will contain the http headers from the request. This value will
    // be used in the audit broker to ensure we are auditing only the allowed
    // headers.
    Headers map[string][]string `json:"headers" structs:"headers" mapstructure:"headers" sentinel:""`

    // Connection will be non-nil only for credential providers to
    // inspect the connection information and potentially use it for
    // authentication/protection.
    Connection *Connection `json:"connection" structs:"connection" mapstructure:"connection"`
```

I think though, each backend might need to do it as there's no common helper called by them all -- `PopulateTokenAuth` doesn't take enough parameters (namely the request) to do it itself and updating that parameter would break external auth plugins. 

My 2c. :-)
