### ISSUE TITLE
Update documentation to include absence of web-ui 

### ISSUE THREAD

**Issue by JPBeltman** [openbao/openbao#335]
As per [Pull 190](https://github.com/openbao/openbao/pull/190), the webui is no longer available in current release (OpenBao v2.0.0-alpha20240329), the openbao configuration documentation does not reflect this.

Requesting some sort of warning or banner beneath the [OpenBao Configuration](https://openbao.org/docs/configuration/) and/or [OpenBao UI](https://openbao.org/docs/configuration/ui/) header for clarity.

**Comment by JanMa** [comment]
Thanks for opening the issue @JPBeltman, I thought we mention this in our alpha release notes, but as it turns out we do not. I'll add a warning banner :+1:
