### ISSUE TITLE
How should OpenBao treat mlock?

### ISSUE THREAD

**Issue by IohannesArnold** [openbao/openbao#352]
The Vault Docs, which have been inherited by OpenBao, give a very confusing message regarding the `disable_mlock` setting. [First they say](https://openbao.org/docs/configuration/#parameters):
> Disabling `mlock` is not recommended...

Then they say:
> Disabling `mlock` is strongly recommended if using [integrated storage](https://openbao.org/docs/internals/integrated-storage/)

Logically, this is not contradictory (general recommendation followed by particular exception) but rhetorically the change between the two paragraphs leaves me uncertain. I would have expected a "conversely" or something in the second sentence.

Adding to the potential for confusion, it is now the case that for OpenBao, integrated storage is the single native production-level storage backend, and [all others have been moved to external plugins](https://github.com/openbao/openbao/issues/134). So if I understand things correctly, at present the single recommended storage backend requires that you set `disable_mlock` to `true`, although the default value for this setting is `false`.

I can think of a few fixes to this, each stronger than the next:
 1. Edit the docs to clarify what the recommended settings are for OpenBao.
 2. Edit the code to have `disable_mlock` default to `true`.
 3. Edit the code to rename the setting to avoid the double negative -- i.e. change it to `enable_mlock`, with a default of `false`.

**Comment by cipherboy** [comment]
Hmm, this is interesting.

https://support.hashicorp.com/hc/en-us/articles/115012787688-Vault-and-mlock seems to suggest that `disable_mlock=false` should be preferred as swapping memory could lead to secrets appearing in disk in plaintext. However, I think [the bbolt docs](https://pkg.go.dev/go.etcd.io/bbolt#DB) gives some context as to why this might be bad:

> ```go
> 	// Mlock locks database file in memory when set to true.
> 	// It prevents major page faults, however used memory can't be reclaimed.
> 	//
> 	// Supported only on Unix via mlock/munlock syscalls.
> 	Mlock bool
> ```

In particular, I think this means that we can see unbounded memory growth if a large number of storage records are created+deleted. To test this hypothesis, I think we can use [`vault-benchmark`](https://github.com/hashicorp/vault-benchmark) to create a bunch of K/V mounts and then delete them and see if memory eventually gets reclaimed by the OS if it needs it.

I wonder, can `disable_mlock=false` be the default, but a separate option `Mlock=false` be set on bbolt? 

I think this warrants additional investigation. Are you willing to tackle this perhaps, @IohannesArnold? 

---

I think we'll probably leave this (admittedly confusing) behavior though, perhaps with cleanups. As discussed in #270, it'd be great to have a proper database as a (single) alternative; I have a local branch with PostgreSQL support. But have not yet had the time to clean up #292 and get that merged, which I'd like to do before reintroducing PostgreSQL.

**Comment by IohannesArnold** [comment]
A few more thoughts & observations:

When configured, Mlock is only called once, [here in out code](https://github.com/openbao/openbao/blob/99fc5658fcaeb62e6209d47ec8c470d2092f1d5c/vault/core.go#L1060), which ends up being [here in a (Hashi) library](https://github.com/hashicorp/go-secure-stdlib/blob/90fcdf1d959f524fd6960134ed0a0d8096db2c81/mlock/mlock_unix.go#L20). The syscall tells Linux to lock **all** process memory, both that currently allocated and all memory allocated in the future.

bbolt has its own Mlock feature, but that's not used at all by OpenBao; bbolt will just inherit the mlock settings by being in the same process. But I wonder if we could get a PR merged in bbolt to add a `force_munlock` option or something similar, so that [every time it ran mmap](https://github.com/etcd-io/bbolt/blob/f663d4e6043e37fa77c3b554f2692d4d02cc8c95/bolt_unix.go#L57), it would munlock the relevant pages.

If we could do that, then we could use Integrated Storage with mlock for the rest of process memory.

**Comment by cipherboy** [comment]
@IohannesArnold that sounds like a great improvement! Let me know if there's anything I can do to help with that.

**Comment by IohannesArnold** [comment]
Okay, here is the issue I've opened at bbolt to get started with this solution:
https://github.com/etcd-io/bbolt/issues/760

**Comment by cipherboy** [comment]
@IohannesArnold Hmmm... With the fork of bbolt, I don't know how viable it is, tbh. Given you enable mlock globally in Vault, and to then mmap a 100GB+ bbolt db file into memory without swapping, you need that much memory... I don't know that forking bbolt here does what we want either. I suspect making storage be a separate process and using GRPC for it might actually be a better approach here.

There's some overhead with GRPC, I will admit, but on-system perhaps it is low enough not to worry? Thoughts?

I think at least making this a proper RFC and inviting more input on it would be useful, even if we leave the documentation the way it is (clarifying why this is a hard problem and why the recommendation is the way it is).

**Comment by IohannesArnold** [comment]
> Given you enable mlock globally in Vault, to then mmap a 100GB+ bbolt db file into memory without swapping, you need that much memory... I don't know that forking bbolt here does what we want (munlock after the mmap will still require that 100GB+ memory up-front).

Sorry, yes, I should have added here that my strategy of `munlock`'ing bbolt's mmap also requires adding the `MCL_ONFAULT` flag to the original `mlockall` call. With that added, the 100GB db mmap will not be paged in at first creation, and the subsequent munlock call will allow the pages that are paged in to be returned to disk.

> making this a proper RFC and inviting more input on it

What does this entail?

**Comment by cipherboy** [comment]
> > making this a proper RFC and inviting more input on it
> 
> What does this entail?

I'd fill out [the RFC form](https://github.com/openbao/openbao/issues/new?assignees=&labels=rfc%2Cpending-decision&projects=&template=rfc.yml) which should start a new issue with the relevant information. I think #140 and #296 could be good references for complete versions :-)

**Comment by IohannesArnold** [comment]
Okay, closing this issue in favor of [the RFC](https://github.com/openbao/openbao/issues/354)

**Comment by daipok** [comment]
I coincidentally came to this note, and found in my log:
[WARN]  unknown or unsupported field disable_mlock found in configuration at /etc/openbao/openbao.hcl:1:1

This field is not supported ?

**Comment by cipherboy** [comment]
@daipok Yes, it was removed. See https://openbao.org/docs/rfcs/mlock-removal/ which should have alternatives when running under SystemD that function similarly but don't interfere with Raft.
