### ISSUE TITLE
RFC - Changing OpenBao's usage of mlock

### ISSUE THREAD

**Issue by IohannesArnold** [openbao/openbao#354]
### Summary

To prevent writing sensitive information to disk through swap, Vault used the mlock syscall to prevent any process memory from being swapped out to disk. This never worked perfectly, and while OpenBao has so far retained Vault's usage of mlock, other design decisions made since the fork call the entire mlock design into question.

### Problem Statement

[`mlock` is a Posix syscall that will lock some or all of a process's virtual memory in physical memory and prevent it from being paged out to disk](https://www.man7.org/linux/man-pages/man2/mlock.2.html). This provides a security advantage for applications like OpenBao, which deal with sensitive information. By using `mlock`, OpenBao can ensure that sensitive information stays in memory, instead requiring the deploying sysadmin to securely overwrite, encrypt, or disable swap. For this reason, Vault used `mlock` where possible, and OpenBao has inherited this code so far.

However, for various reasons, discussed in more detail later, `mlock` can not be used in all situations. [It can only be used on Linux and the BSDs](https://github.com/openbao/go-secure-stdlib/blob/main/mlock/mlock_unix.go), [not Windows, macOS, or other platforms](https://github.com/openbao/go-secure-stdlib/blob/main/mlock/mlock_unavail.go). It will also [lead to a bug if it is used with Integrated Storage](https://developer.hashicorp.com/vault/tutorials/operations/performance-tuning#mlock), so while enabling `mlock` usage on Linux with Integrated Storage is _possible_, [it is discouraged by Vault](https://developer.hashicorp.com/vault/docs/configuration#disable_mlock), and so far [this has been retained by OpenBao](https://openbao.org/docs/configuration/#parameters).

As part of the fork, [all external storage options were removed from OpenBao](https://github.com/orgs/openbao/discussions/64), leaving the Integrated Storage as the sole production-quality storage backend. As a result, in the current state of the codebase, there are **zero** production-level configurations where it is advisable to have `mlock` enabled. Nevertheless, `mlock` is _enabled_ by default on those platforms which support it. This seems less than ideal, and the purpose of this RFC is to discuss how OpenBao's usage of `mlock` might evolve in a more elegant direction.

### User-facing description

Configuring `mlock` is only relevant to sysadmins maintaining the OpenBao server process. Since it is enabled on Linux by default, they must read the docs (currently rather unclear on this point) to learn that they should disable it. Disabling it requires a single line in the server config.

Incidentally, if `mlock` is left _enabled_, it still may not work out of the box. The Linux kernel limits by default a process's ability to call `mlock`, and if this capacity is not granted (typically though a line in the systemd service file), then OpenBao will exit with an error on startup. But if `mlock` is successfully enabled, then since OpenBao only supports Integrated Storage at present, it will attempt to load its entire database into physical memory. If the size of the database exceeds the amount of physical memory, the OOM killer will be forced to kill the OpenBao process, possibly also taking other processes down along the way.

### Technical Description

The root cause of many of the complications brought up in this RFC has to do with the interaction between `mlock` and Go memory allocation. Classically, in C, `mlock` is only called on a specific region of memory where sensitive information is being stored; all other memory is left free to be paged back to disk. However, this is not possible with Go because:
> [go's garbage collector can and will move and copy memory as it sees fit. `mlock` on a go-managed buffer just prevents the original memory location from being swapped out to disk, but does nothing to the copies that the go runtime will periodically create.](https://news.ycombinator.com/item?id=14174500)

To work around this, `mlock` was originally implemented in Vault through the specific call [`mlockall(MCL_CURRENT|MCL_FUTURE)`](https://github.com/openbao/go-secure-stdlib/blob/e238ea0d4570f814e033ba4fec10636735ba0bc0/mlock/mlock_unix.go#L20), which told the kernel to lock **all** memory in the process's **entire** address space. This worked fine for most backends, but doesn't work for the Integrated Storage backend, because bbolt, the library it uses for its database, [`mmap`s the entire database file](https://github.com/etcd-io/bbolt/blob/f663d4e6043e37fa77c3b554f2692d4d02cc8c95/bolt_unix.go#L57). Since this happens in the same process, the database `mmap` interacts with the prior `mlockall` setting in a diabolical way: the _entire_ database is loaded into physical memory immediately upon creation of the `mmap`. If the size of the database exceeds the amount of physical memory available to the OS, bad things happen.

Notice, however, that all of this is just a means to an end. The original goal of all of this was to prevent a secret that was resident in memory from being written to disk on a swap partition, and then being sniffed from swap. But there are other ways to prevent this data leak. Swap can be disabled across the entire OS; swap can be encrypted; swap can be disabled for one process in particular through the [cgroupv2 setting `memory.swap.max`](https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v2.html). These methods are at least as equally good as `mlock`, if not better, because without `mlock`, the kernel can return to disk little-used pages in process memory, such as portions of the (rather chunky) OpenBao binary.

### Rationale and alternatives

I will provide five options here: four for the short term and one for the long term. The four short term options are somewhat mutually exclusive; none of the short term options are exclusive of the long term option.

#### Option 1: Rip `mlock` out entirely

Since there is currently **no** circumstance where it is advisable to run OpenBao in production with `mlock` enabled, just rip `mlock` out of OpenBao. There's already been a lot of ripping code out as part of the fork, so this would be one removal among many. The `mlock` feature was never well-designed -- it didn't work on all platforms or for all storage backends. Calling `mlockall` in a complex application like this is simply a code smell. Right now, it's causing trouble with bbolt, but it may pose other problems in the future, where it might threaten other negative interactions with other proposed features. Save everyone the trouble and rip it out now while it's the season to be ripping stuff out.

Instead, add a "Hardening OpenBao" section to the docs which discusses alternatives such as disabling swap. This has the added benefit of also indicating this vulnerability to Windows and macOS users, who right now are simply told "no mlock for you!" in the docs but are not given any indications what the consequences of this might be. I don't know what the equivalent to disabling swap is for Windows, but if the docs addressed it more specifically, someone with Windows knowledge might come along and add that info, which will make OpenBao on Windows more secure than it's been before.

#### Option 2: Fork bbolt and add `munlock`
There are two steps to this. The first step is to add the flag `MCL_ONFAULT` (only on Linux > 4.4) to the `mlockall` call. This flag changes the locking behavior so that instead of loading and locking a `mmap` page into physical memory upon creation, a memory page is only loaded upon first access, like normal, and then locked.

The second step is to fork the upstream bbolt library and add a one-line patch to it, so that immediately after creating the db `mmap`, that specific region of memory is then `munlock`ed. This will prevent (on Linux > 4.4) the specific error that shows up with `mlock` and bbolt. It involves forking an upstream library, but only to add a one-line patch. [They're not interested in mainlining such a patch upstream](https://github.com/etcd-io/bbolt/issues/760).

#### Option 3: Move the storage backend into a separate process

This would involve moving the storage backend code into a separate process which would not have to deal with the effects of `mlockall` called by the main OpenBao process. That solves the problem well enough. Coming up with the right IPC design for storage IO all happening in another process is likely to be tricky, but if this is solved, it will also have the beneficial consequence of making it easier for the community to create third party storage backends.

#### Option 4: Do nothing

Insofar as OpenBao is just a drop-in replacement for Vault, not doing anything is feature-for-feature and bug-for-bug compatible with Vault 1.14. We can edit the docs to clarify things a bit more and call it a day.

#### Long term option: design secure memory enclave

Recall that the reason you must call `mlockall` instead of locking a specific region of memory is because Go's automatic memory management will normally move objects around; they don't have fixed addresses. But if there were a way to get memory allocations in a specific region, then instead of calling `mlock` on the entire process address space, there would be a specific memory rage that would get `mlock`ed, and there would be a "secure allocator" which would only allocate from that space and all sensitive data could then use that allocator to make sure their memory location was in the secure enclave.

I'm not a Go wizard, so I'm not sure there's a way to drop down to this level of manual memory management in Go, or if you'd have to do it in C, Rust, or Zig. In case of the latter, I realize that creates the burden of a polyglot project. But the reward is that OpenBao would have a much smaller, focused enclave of secret material, which could be protected on more platforms (like [Windows](https://github.com/openbao/go-secure-stdlib/blob/e238ea0d4570f814e033ba4fec10636735ba0bc0/mlock/mlock_unavail.go#L15)), and also, possibly, through more methods, like in-memory encryption via TPM2, Linux Kernel keyring, or AMD SME.

I don't think this is urgent, which is why I'm not suggesting to do this now; I'm just raising the possibility for the long-term evolution of OpenBao.

**Comment by IohannesArnold** [comment]
>While I concur here from a practical standpoint, I think it's hard to argue that `mlock` provides no benefits. Secure enclaving technology, while interesting, likely limits platform adoption. Pieces like Agent or Proxy also benefit from mlock and may run in containers or other lower resourced systems. So on the whole, I'd be in favor of leaving mlock support even if confusing.

I certainly do not claim that `mlock` provides no benefits, just that its benefits are not unique to it. In particular, you can get _exactly_ the same benefit as using `mlock` by using cgroups. This also takes exactly the same amount of effort: to use `mlock`, you **must** have the line `LimitMEMLOCK=infinity` in your systemd service file; but you can disable per-process swap (the exact same benefit) with the single line `MemorySwapMax=0`.

Also, I should note that `mlock` is _not_ used in the Agent or Proxy, just the server, in the current codebase. You can see there's not a config option for it and I can confirm this experimentally. But I agree that it's easy to get the mistaken impression that `mlock` _is_ implemented for the Agent and Proxy. I would argue this is another reason to say the current `mlock` implementation is deeply broken and should be ripped out and users pointed to other solutions that provide the same benefits.

To your other points, I agree. I think there could be a three step evolution here: 1) Immediate term -- rip out `mlock` & point to other solutions 2) Short/Mid term -- move storage backend to separate process 3) Mid/Long term -- re-implement `mlock`  better, perhaps with broader consideration of manual memory management.

**Comment by cipherboy** [comment]
@IohannesArnold said:
> I certainly do not claim that `mlock` provides no benefits, just that its benefits are not unique to it. In particular, you can get _exactly_ the same benefit as using `mlock` by using cgroups. This also takes exactly the same amount of effort: to use `mlock`, you **must** have the line `LimitMEMLOCK=infinity` in your systemd service file; but you can disable per-process swap (the exact same benefit) with the single line `MemorySwapMax=0`.

Oh certainly, I wasn't trying to imply you did. It is interesting to hear this about cgroups though. My understanding for `mlock` was that it was a requirement for OpenShift certification/compliance. I don't see it listed [here](https://access.redhat.com/documentation/en-us/red_hat_software_certification/2024/html/red_hat_openshift_software_certification_policy_guide/assembly-requirements-for-container-images_openshift-sw-cert-policy-introduction), but I'm not sure I'm looking in the right place... If cgroups can meet the requirements and are accessible within the workload running on OpenShift, and is as easy to do... this could be as good if not better.

> But I agree that it's easy to get the mistaken impression that `mlock` _is_ implemented for the Agent and Proxy.

Interesting... TIL! Thank you :D I think perhaps implementing this functionality could be useful? They explicitly spill secrets onto disk in many cases, but limiting this to known areas seems... better? With modern HDD/SSD drives, you'd almost certainly want it to be an encrypted location if you're worried about data destruction (lose a key vs trying to ensure specific sectors are _actually_ overwritten).


---

Do we want to put the cgroups as an alternative here? Rip `mlock` out but replace it with the cgroup style protection as a suggestion that works in all cases? Thoughts?

**Comment by IohannesArnold** [comment]
>Rip `mlock` out but replace it with the cgroup style protection as a suggestion that works in all cases?

That's what I'm leaning towards (non-exclusive of also factoring storage into another process). But are there other voices that are going to chime in here?

**Comment by DanGhita** [comment]
Well, I think the general topic here is how to improve the protection in RAM of the sensitive data manipulated by Vault. And this is a complicated topic, usually addressed by embedded security experts.
While I’m not an expert in Linux hardening, I think built-in security mechanisms (Linux cgroup and namespace) could provide, indeed, an extra layer of protection.
But in any case, that would probably require a re-architecture of the Vault, in order to separate the code manipulating sensitive data (keys, secrets, etc.) and have a better control over the memory hosting these sensitive data. Just an example: we should probably guarantee that the memory zone, where a private key has been manipulated, is properly reset with zeros/random values. Or it seems that currently we cannot really achieve this: if I’m not wrong, mainly because Go does not allow a direct control of the memory (and yes, I agree, most of the time this is for our own good).

**Comment by IohannesArnold** [comment]
> If you haven't seen the [OpenBao Community calls](https://lists.lfedge.org/g/openbao/topic/106463374?p=%2C%2C%2C20%2C0%2C0%2C0%3A%3ACreated%2C%2C%23cal-reminder%2C20%2C2%2C0%2C106463374%2Cct%253D1&ct=1), they are today at 11AM Eastern and that's probably the best place to get a larger audience for this. I can bring it up if you can't make it (recordings are publicly available).

I wasn't able to make it and I can't find the recordings; how was it?

> But in any case, that would probably require a re-architecture of the Vault, in order to separate the code manipulating sensitive data (keys, secrets, etc.) and have a better control over the memory hosting these sensitive data. Just an example: we should probably guarantee that the memory zone, where a private key has been manipulated, is properly reset with zeros/random values. Or it seems that currently we cannot really achieve this: if I’m not wrong, mainly because Go does not allow a direct control of the memory (and yes, I agree, most of the time this is for our own good).

I agree this is the looooooooooooong term solution, but for the short term the proposal is to swap out the buggy mlock implementation with cgroups.

**Comment by cipherboy** [comment]
@IohannesArnold Apologies for the delay; this was discussed on [last week's call (recording)](https://zoom.us/rec/share/iwEQb0_wgY9D03ck-gKCL5rM1TdJiBQoRggfDVwpakEXiwE8Z7BnRmf_B1rHegg8.NuPGOQ0Epfy49TXb) --- it hasn't yet been added to the [past meetings recordings](https://wiki.lfedge.org/display/OH/OpenBao+Meetings) though.

I think there were no objections here; I initially brought it up as replacing mlock with the cgroup alternative which I think, thinking about it more, makes more sense than trying to keep & save mlock. Making storage external or the more invasive secure enclave/... approach would definitely be more work for later, IMO, and not worth our immediate time.

Thoughts? :-)

**Comment by IohannesArnold** [comment]
That sounds good:

Now -- rip out mlock and replace with recommendation to use cgroups

Mid/Long term -- Move storage operations to external process

Very long term -- Research secure memory enclave

---

I'll work on a PR to rip out mlock code and change the docs and example service file in `.release/linux/package` to recommend cgroups.

**Comment by JanMa** [comment]
I only got around to reading your RFC now, thank you for putting it together @IohannesArnold . I am in favor of removing OpenBao's use of `mlock` and support the process outlined in the previous comments

> Now -- rip out mlock and replace with recommendation to use cgroups
> Mid/Long term -- Move storage operations to external process
> Very long term -- Research secure memory enclave

**Comment by cipherboy** [comment]
@IohannesArnold What do you think about closing this? I think the medium to long term items don't block this RFC and both probably are large enough to warrant separate RFCs entirely.

Do you mind opening this as a PR to the documentation branch? See https://github.com/openbao/openbao/pull/170/commits/cf6ce4819b6e63669a289afb447aaa20dc6f877d for example.

**Comment by IohannesArnold** [comment]
Sure, once the RFC is added to the docs I think this conversation has served its purpose.
