### ISSUE TITLE
Docker image does not contain UI

### ISSUE THREAD

**Issue by credbbl** [openbao/openbao#357]
**Describe the bug**
The Docker image does not contain the UI part of the application. It just links to https://www.vaultproject.io/downloads.html

**To Reproduce**
1. Run `podman run --rm --net host -e SKIP_SETCAP=true -ti quay.io/openbao/openbao:2.0.0-alpha20240329`
3. Access http://localhost:8200/ui/

**Expected behavior**
The binaries in the Docker image are usable in the documented way.

**Comment by nettnikl** [comment]
For reference, overall tracking is currently in https://github.com/openbao/openbao/issues/739.
