### ISSUE TITLE
OpenBao Beta shows wrong version

### ISSUE THREAD

**Issue by JanMa** [openbao/openbao#400]
**Describe the bug**
The OpenBao Beta version still reports itself as the Alpha version when running `bao version`

**To Reproduce**
1. Download and extract the OpenBao Beta binary
2. Run `bao version`

The output will show `OpenBao v2.0.0-alpha20240329`

**Expected behavior**
The binary should report the version as `OpenBao v2.0.0-beta20240618`

**Comment by cipherboy** [comment]
@JanMa `version/VERSION` will need to be updated I think.
