### ISSUE TITLE
Consider not installing binary to $GOBIN / $GOPATH during build

### ISSUE THREAD

**Issue by Ikke** [openbao/openbao#402]
**Is your feature request related to a problem? Please describe.**

I'm working on packaging OpenBao for Alpine Linux (just a test for now until it's released). The `scripts/build.sh` script will copy the built binary to $GOBIN. When packaging projects, this is unexpected / undesired.

**Describe the solution you'd like**

Support the common workflow of separate build and install steps. The install step should support a custom destination (DESTDIR + prefix) where the files are installed to so that they can be packaged and later installed to the correct locations.

**Describe alternatives you've considered**

An alternative solution would be to not install anything and defer that step to individual packagers. With a single file, this is a feasible option, but once there are more files (ui, documentation, etc), this becomes unwieldy.

**Explain any additional use-cases**
N/A

**Additional context**
N/A

**Comment by JanMa** [comment]
Hello @Ikke, thanks for your interest in packaging OpenBao! We moved our build and release pipeline to [Goreleaser](https://goreleaser.com/) for our Alpha release and the `build.sh` script is mostly obsolete. It just hasn't been cleaned up yet. Goreleaser seems to support Alpine packages as well, so we could add the relevant settings to our config file. Would you be able to use those packages or do you want/need to build and package the binary yourself?

**Comment by Ikke** [comment]
In Alpine Linux, we build everything from source and do not redistribute existing binaries / packages, and other distributions have similar requirements. 

So it would be appreciated if that use case can be considered.

**Comment by cipherboy** [comment]
@Ikke `goreleaser` just calls `go build` with a few arguments, so you should be able to do that for Alpine.

**Comment by JanMa** [comment]
Understood @Ikke, thanks for clarifying this. I will look into it to support distributions wanting to package OpenBao :+1:

**Comment by cipherboy** [comment]
Closing per advice here:

> just call~s~ `go build` with a few arguments

The `Makefile` is provided for development convenience and we intend to keep `go build` working for the foreseeable future, +/- UI building (which isn't handled by `scripts/build.sh` anyways).
