### ISSUE TITLE
Consider supporting building outside of git repository

### ISSUE THREAD

**Issue by Ikke** [openbao/openbao#403]
**Is your feature request related to a problem? Please describe.**

When trying to build OpenBao from the source archive, `scripts/build.sh`  fails with:

```
fatal: not a git repository (or any of the parent directories): .git
```

Because it tries to run git commands while there is no repository

**Describe the solution you'd like**

Support the use case of building the project outside of it's git repository. Information about which commit was used to build is not available, but the tagged version should suffice in most cases.

For the build date, consider supporting `SOURCE_DATE_EPOCH`, which is a standard environment variable to support [reproducible builds](https://reproducible-builds.org/docs/source-date-epoch/). 

**Describe alternatives you've considered**

Alternatively projects could patch the `build.sh` script to not invoke any git commands. These patches would need to be kept up-to-date when the script gets modified, and could lead to differences in how it is handled by different packages.

**Explain any additional use-cases**

It is common while packaging a project to use the source archives and not clone the original repository. Supporting this way of building makes it easier to package the project in various distributions.

**Additional context**
N/A

**Comment by cipherboy** [comment]
As in #402, the proper solution would be to rely on `go build` and stub the values of the relevant git-inferred constants. This is what we do at GitLab: https://gitlab.com/gitlab-org/govern/secrets-management/openbao-internal/-/blob/main/Makefile
