### ISSUE TITLE
Clean up obsolete build scripts

### ISSUE THREAD

**Issue by JanMa** [openbao/openbao#404]
We moved our build and release pipeline to Goreleaser for the Beta release. We should clean up any old an no longer needed build scripts and also adjust the Makefile to use Goreleaser to build the binary.

**Comment by cipherboy** [comment]
@JanMa Do we want to use goreleaser to build for local development? It seems like overkill.

**Comment by cipherboy** [comment]
Going ahead and closing this one. I think substantial build process cleanup has already been done since this was mentioned. 

Using `go build` directly is IMO preferable for local development than requiring people install `goreleaser`.
