### ISSUE TITLE
Add Support for riscv64

### ISSUE THREAD

**Issue by liberodark** [openbao/openbao#42]
Hi,

I know it's going to take you a while before you make a release.
But I would like you to consider releasing support for riscv64.
Also I propose to provide riscv64 servers if necessary.

Best Regards

**Comment by cipherboy** [comment]
It looks like Go toolchain already supports riscv64; it'd be interesting to see what fails if you attempt a build @liberodark. I don't presently have access to riscv hardware ATM, though could try playing with emulation sometime.

**Comment by liberodark** [comment]
Hi, if you want i can give you access on riscv64 hardware for free.
Also have build apps in go on riscv64 hardware with success.
My Goal is to open cluster riscv64 server for developpers want to access on riscv64 hardware and that for free.

**Comment by liberodark** [comment]
My build : 

```
apt install -y golang-go rsync gpg git nodejs npm
git clone https://github.com/openbao/openbao
cd openbao
git checkout development
go build
```

**Comment by cipherboy** [comment]
@liberodark This looks good :) I think then, when we get more mature and have CI up and running, we'll want to sync on getting access to these RISC-V build machines and setting up a CI/testing pass on them, but in the mean time, I think we can call this good to start!

**Comment by liberodark** [comment]
Im adding link of website if you want access to RISC-V hardware : https://open-riscv-initiative.com/

**Comment by cipherboy** [comment]
@liberodark I finally got around to fixing the build pipelines, #168 should add RISC-V support for you :-)
