### ISSUE TITLE
Release support policy

### ISSUE THREAD

**Issue by chenrui333** [openbao/openbao#426]
👋 Congrats on the 2.0.0 GA release, is any docs about the stable release support policy? Thanks!

**Comment by cipherboy** [comment]
Hi @chenrui333 -- can you clarify what you mean by "support policy"? We are volunteers who work on this project and there is no formal support contract one can acquire. However, we do intend to fix issues with the project and aim to be compatible with previous releases (roughly) according to SemVer.

**Comment by chenrui333** [comment]
yeah, I understand the OSS nature, but I am curious if there would be some sort of EOL release managements like https://support.hashicorp.com/hc/en-us/articles/360021185113-Support-Period-and-End-of-Life-EOL-Policy

FWIW, I filed a similar issue with opentofu, and it might help things a bit, `https://github.com/opentofu/opentofu/issues/1099`

@cipherboy let me know if you need me to provide more info

(disclaimer, I am a maintainer for `endoflife.date` project, and I want to help include openbao into it. )

**Comment by cipherboy** [comment]
\o hey @chenrui333! This was resolved in https://github.com/openbao/openbao/pull/615 and should be available from https://openbao.org/docs/policies/support/. Thank you for bringing this to our attention.

**Comment by adriens** [comment]
https://openbao.org/docs/policies/support/

<img width="841" height="514" alt="Image" src="https://github.com/user-attachments/assets/131c9967-9ccf-48ca-87c7-8c7c515920a7" />

**Comment by adriens** [comment]
🤞 
- https://github.com/endoflife-date/endoflife.date/pull/8374

**Comment by adriens** [comment]
- https://github.com/openbao/openbao/issues/1791
