### ISSUE TITLE
Create a FreeBSD Port

### ISSUE THREAD

**Issue by CyberCois** [openbao/openbao#431]
**Is your feature request related to a problem? Please describe.**
OpenBao is not available in the FreeBSD ports tree. 

**Describe the solution you'd like**
Add OpenBao to the FreeBSD ports tree. 

**Describe alternatives you've considered**
The alternative would be to fetch the pre-compiled binary (or compile manually) and write a custom RC script to install and run Vault.

**Explain any additional use-cases**
If there are any use-cases that would help us understand the use/need/value please share them as they can help us decide on acceptance and prioritization.
A FreeBSD port is only allowed to to have network during the pre/post fetch build phase. This is for security reasons and has caused issues with porting node applications. 
1.  I would request port versioning if openbao is going to have multiple maintained major versions released at the same time.
2. A build option to disable the UI (for future openbao releases which will include the UI)

**Additional context**
There is an existing port of Vault. The process should be similar for openbao.
https://www.freshports.org/security/vault

**Comment by cipherboy** [comment]
\o hello @CyberCois -- we're happy to have a port done and happy to work with any maintainers to do so. :-) However, we may not ourselves get to this work. As discussed in #402, I suggest directly calling `go build` and not relying on development build scripts for reproducibility.

**Comment by CyberCois** [comment]
@cipherboy Thanks you! I created a new port using `go build` as you've suggested. I've submitted it for approval here: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=280619

**Comment by CyberCois** [comment]
Port created! https://www.freshports.org/security/openbao

**Comment by cipherboy** [comment]
Thank you @CyberCois! Do you want to add it to the docs page? Otherwise I can go ahead and do so tomorrow.
