### ISSUE TITLE
Cannot set custom JSON configuration with Docker

### ISSUE THREAD

**Issue by jackhodgkiss** [openbao/openbao#445]
**Describe the bug**
When attempting to use to the Docker image `openbao/openbao:2.0.0` and provide custom JSON configuration via the variable `BAO_CLUSTER_ADDR` as described in the [docker-entrypoint.sh](https://github.com/openbao/openbao/blob/main/scripts/docker/docker-entrypoint.sh#L43C24-L43C40) it will fail.

The error message produced is

```
Error parsing cluster address {"cluster_name": "openbao_clstr", "ui": false, "api_addr": "http://10.10.11.14:8200", "cluster_addr": "http://127.0.0.1:8201", "listener": [{"tcp": {"address": "10.10.11.14:8200", "tls_disable": "true"}}, {"tcp": {"address": "127.0.0.1:8200", "tls_disable": "true"}}], "storage": {"raft": {"node_id": "raft_01", "path": "/openbao/file"}}, "telemetry": {"prometheus_retention_time": "30s", "disable_hostname": true}}: parse "{\"cluster_name\": \"openbao_clstr\", \"ui\": false, \"api_addr\": \"http://10.10.11.14:8200\", \"cluster_addr\": \"http://127.0.0.1:8201\", \"listener\": [{\"tcp\": {\"address\": \"10.10.11.14:8200\", \"tls_disable\": \"true\"}}, {\"tcp\": {\"address\": \"127.0.0.1:8200\", \"tls_disable\": \"true\"}}], \"storage\": {\"raft\": {\"node_id\": \"raft_01\", \"path\": \"/openbao/file\"}}, \"telemetry\": {\"prometheus_retention_time\": \"30s\", \"disable_hostname\": true}}": invalid URI for request
```

I believe this is due to the improper change on [L43](https://github.com/openbao/openbao/blob/main/scripts/docker/docker-entrypoint.sh#L43C24-L43C40)-[L47](https://github.com/openbao/openbao/blob/main/scripts/docker/docker-entrypoint.sh#L47) where the variable should been renamed from `VAULT_LOCAL_CONFIG` -> `BAO_LOCAL_CONFIG` rather than `BAO_CLUSTER_ADDR` which is used earlier in [the script](https://github.com/openbao/openbao/blob/main/scripts/docker/docker-entrypoint.sh#L30). 

**To Reproduce**
1. Create local variable containing JSON configuration `export BAO_CLUSTER_ADDR=...`
2. Run Openbao docker container image `docker run -dit -e BAO_CLUSTER_ADDR=$BAO_CLUSTER_ADDR openbao/openbao:2.0.0 server`
3. See logs by following container `docker logs --follow CONTAINER_NAME` 

**Expected behavior**
I expect to be to able to provide custom JSON configuration via a supported environment variable.

**Environment:**
* OpenBao Server Version (retrieve with `bao status`): 2.0.0
* OpenBao CLI Version (retrieve with `bao version`): 2.0.0
* Server Operating System/Architecture: Rocky 9.4 host and [Linux/AMD64 container](https://hub.docker.com/layers/openbao/openbao/2.0.0/images/sha256-bdd0f74946f0fe2b5d69761886fb7a6bae6b5e90d1562937aa046cb3ece90e4d?context=explore) 

OpenBao server configuration file(s):

```json
{"cluster_name": "openbao_clstr", "ui": false, "api_addr": "http://10.10.11.14:8200", "cluster_addr": "http://127.0.0.1:8201", "listener": [{"tcp": {"address": "10.10.11.14:8200", "tls_disable": "true"}}, {"tcp": {"address": "127.0.0.1:8200", "tls_disable": "true"}}], "storage": {"raft": {"node_id": "raft_01", "path": "/openbao/file"}}, "telemetry": {"prometheus_retention_time": "30s", "disable_hostname": true}}
```

**Comment by cipherboy** [comment]
I don't disagree with this issue, but it only happens from `make docker`? I think the release is unaffected as `goreleaser` uses the other version? https://github.com/openbao/openbao/blob/232f86e686008b6869c40635b7be918d4c7fbd8f/.goreleaser-template.yaml#L263
