### ISSUE TITLE
AWS Lambda Extension - keep or remove?

### ISSUE THREAD

**Issue by JanMa** [openbao/openbao#47]
Upstream Vault maintains an AWS Lambda Extension which allows Lambda functions to read secrets from a Vault cluster. This Extension is explicitly mentioned in the [official documentation](https://developer.hashicorp.com/vault/docs/platform/aws/lambda-extension) which begs the question: Are we going to fork and keep it or remove the relevant docs?

**Vote**:
:+1:  to keep it
:-1:  to remove it.

**Comment by cipherboy** [comment]
Like our discussion about the SSH helper, I imagine that this exclusively uses public APIs and can be left unforked.

**Comment by naphelps** [comment]
Support of any feature or function is organic if there is community willing to support it.

**Comment by cipherboy** [comment]
@naphelps agreed, but note that in this case, we're unlikely to see many benefits of forking rather than directly contributing upstream here, for this particular package.

**Comment by naphelps** [comment]
@cipherboy Agreed.

**Comment by vamsinm** [comment]
we modeled off of [extension](https://aws.amazon.com/blogs/compute/caching-data-and-configuration-settings-with-aws-lambda-extensions/) from aws and updated to use for vault. advantage of this extension is you dont need to load vault specifi apis and secrets are stored in memory instead of disk.

**Comment by JanMa** [comment]
Closing as we chose to remove the docs in 27f0d4d7f213ca9ad57b97f56d6e184c4fc8cda8
