### ISSUE TITLE
api: drop dependency on go-rootcerts (Vault #26136)

### ISSUE THREAD

**Issue by cipherboy** [openbao/openbao#484]
@dolmen writes on [#26136](https://github.com/hashicorp/vault/issues/26136)

> The [`github.com/hashicorp/go-rootcerts`](https://pkg.go.dev/github.com/hashicorp/go-rootcerts) module doesn't seem necessary anymore with recent Go versions:
> 
>     * The package was initially created to workaround a _Darwin-only_ [bug](https://github.com/golang/go/issues/14514) that has been fixed in Go 4 years ago
> 
>     * I filled a question about the relevance of that module ([Is this module still needed? go-rootcerts#21](https://github.com/hashicorp/go-rootcerts/issues/21)) almost one year ago, and nobody replied. Obviously nobody is maintaining that module.
> 
>     * Dropping this dependency will also remove a dependency on [`github.com/mitchellh/go-homedir`](https://pkg.go.dev/github.com/mitchellh/go-homedir) (see also [Use os.UserHomeDir() (darwin) and drop dependency on go-homedir (all) go-rootcerts#22](https://github.com/hashicorp/go-rootcerts/pull/22) about another way to drop that dependency)
> 
> 
> ```
> $ cd api
> $ go mod graph | grep go-rootcerts          
> github.com/hashicorp/vault/api github.com/hashicorp/go-rootcerts@v1.0.2
> github.com/hashicorp/go-rootcerts@v1.0.2 github.com/mitchellh/go-homedir@v1.1.0
> github.com/hashicorp/vault/api@v1.0.5-0.20200519221902-385fac77e20f github.com/hashicorp/go-rootcerts@v1.0.1
> github.com/hashicorp/go-rootcerts@v1.0.1 github.com/mitchellh/go-homedir@v1.1.0
> $ go mod graph | grep go-homedir  
> github.com/hashicorp/go-rootcerts@v1.0.2 github.com/mitchellh/go-homedir@v1.1.0
> github.com/hashicorp/go-rootcerts@v1.0.1 github.com/mitchellh/go-homedir@v1.1.0 
> ```

---

> There are only [a few references](https://github.com/search?q=repo%3Ahashicorp%2Fvault%20rootcerts.Config&type=code) to [`rootcerts.Config`](https://pkg.go.dev/github.com/hashicorp/go-rootcerts#Config) in this repo:
> 
>     * api/client.go
> 
>     * api/ssh_agent.go
> 
>     * builtin/credential/cert/backend_test.go
> 
> 
> If I write the patch myself, is there a chance for it to be accepted?

---

I concur that these APIs can be handled using the standard library and would welcome such a PR here. :-)

**Comment by fatima2003** [comment]
Hi, can I work on this issue?

**Comment by cipherboy** [comment]
Of course! Let me know if you have questions.

**Comment by fatima2003** [comment]
Hi, I am working on removing the module but I was wondering if there is a test I can run besides the ones paired with the file. For instance, running `client_test.go` for `client.go`.  When substituting the code, I found that even if I leave out certain cases, the tests in the paired file were passing. I am following the cases in [rootcerts.go](https://github.com/hashicorp/go-rootcerts/blob/master/rootcerts.go#L1) but just to be extra sure.

**Comment by cipherboy** [comment]
@fatima2003 Yeah, I think `api/client_tests.go` really only exercises one of `EnvVaultCACert` or `EnvVaultCACertBytes` or `EnvVaultCAPath` (whichever one has higher priority and "wins").

It is tricky because `api` shouldn't inherit from the core module (where `helper/` lives) or from `sdk/` (a separate `go.mod`) -- so I think you should place the helper in `api` and the other place (`builtin`) can safely import `api`.

I'd inherit from the system pool and assume the system pool works. Maybe a negative test case, since we're unable to get publicly trusted certs easily (i.e., if you don't set any of the 1-3 options above, and only have the fallback, it fails as expected).

But yes, if you wish to test it properly, I'm all for that :-)

**Comment by fatima2003** [comment]
Hi, I made the changes and ran `go mod tidy` in the appropriate directories and its now removed as a dependency in sdk and a direct dependency in api. 

<details>
<summary>Logs for files it's imported in</summary>

```
fatima openbao % grep -r "github.com/hashicorp/go-rootcerts" .            

./go.mod:       github.com/hashicorp/go-rootcerts v1.0.2 // indirect
Binary file ./bin/bao matches
./go.sum:github.com/hashicorp/go-rootcerts v1.0.2 h1:jzhAVGtqPKbwpyCPELlgNWhE1znq+qwJtW5Oi2viEzc=
./go.sum:github.com/hashicorp/go-rootcerts v1.0.2/go.mod h1:pqUvnprVnM5bf7AOirdbb01K4ccR319Vf4pU3K5EGc8=
./.git/logs/HEAD:fd1511ebdd2085d148a1aa59b5ecb642da085301 915b53e8e0fceb5164dd8a5ecfb5d3174218db16 fp17 <fp17@hw.ac.uk> 1727788343 +0400      commit: github.com/hashicorp/go-rootcerts made indirect
./.git/logs/refs/heads/drop_dependency_on_go-rootcerts_484:fd1511ebdd2085d148a1aa59b5ecb642da085301 915b53e8e0fceb5164dd8a5ecfb5d3174218db16 fp17 <fp17@hw.ac.uk> 1727788343 +0400     commit: github.com/hashicorp/go-rootcerts made indirect
```

</details>

As seen above, it's mentioned in a few previous commits, hashicorps repo as well as in go.mod as an indirect dependency. I investigated the indirect dependency requirement and found that compared to March 25 2024, when the comment was made on hashicorps repo, more stuff have started to depend on github.com/hashicorp/go-rootcerts

**Current Graph** 
```
(base) fatima@fattiesPatties2 openbao % go mod graph | grep 'github.com/hashicorp/go-rootcerts@v1.0.2'

github.com/openbao/openbao github.com/hashicorp/go-rootcerts@v1.0.2
github.com/google/tink/go@v1.7.0 github.com/hashicorp/go-rootcerts@v1.0.2
github.com/hashicorp/go-rootcerts@v1.0.2 github.com/mitchellh/go-homedir@v1.1.0
github.com/openbao/go-kms-wrapping/wrappers/transit/v2@v2.1.0 github.com/hashicorp/go-rootcerts@v1.0.2
github.com/openbao/openbao-template@v1.0.0 github.com/hashicorp/go-rootcerts@v1.0.2
github.com/openbao/openbao/api@v1.9.2 github.com/hashicorp/go-rootcerts@v1.0.2
```

**25 March 2024 Version in [Vault Issue 26136](https://github.com/hashicorp/vault/issues/26136)**

```
$ api % go mod graph | grep go-rootcerts          
github.com/hashicorp/vault/api github.com/hashicorp/go-rootcerts@v1.0.2
github.com/hashicorp/go-rootcerts@v1.0.2 github.com/mitchellh/go-homedir@v1.1.0
github.com/hashicorp/vault/api@v1.0.5-0.20200519221902-385fac77e20f github.com/hashicorp/go-rootcerts@v1.0.1
github.com/hashicorp/go-rootcerts@v1.0.1 github.com/mitchellh/go-homedir@v1.1.0

```
To completely eliminate the module, I am trying to remove it from being depended on in the above files as well but I'm a lil lost on where to start. For instance, this file: github.com/google/tink/go is in a repo that is read only and it depends on github.com/hashicorp/go-rootcerts so unless we stop depending on github.com/google/tink/go@v1.7.0, we won't be able to stop indirectly depending on github.com/hashicorp/go-rootcerts.

**Comment by cipherboy** [comment]
@fatima2003 Nice work!

- `go-kms-wrapping` will be updated once we tag `api` as part of our release process for 2.1.0, so I don't worry about that too much. Same applies for `go-kms-wrpaping`.
- `github.com/google/tink/go` seems deprecated in favor of `github.com/tink-crypto/tink-go/v2`, which doesn't have [go-rootcerts](https://github.com/tink-crypto/tink-go/blob/main/go.mod) as a dependency, so I think you can open a separate PR to update to that and we'll be in fairly good shape!

The old `github.com/openbao/openbao/api` version (`v1.9.2`) will go away once `openbao-template` updates as well. So I think #574 should be fairly good!

**Comment by fatima2003** [comment]
@cipherboy yay, that's good to hear. I will clean this up and open the new PR tmrw!
