### ISSUE TITLE
`output-curl-string` flag returns a string that depends on the `vault` client instead of the `bao` client

### ISSUE THREAD

**Issue by Btijmen** [openbao/openbao#510]
**Describe the bug**
When using the flag `-output-curl-string` with any `bao` command, it returns the curl string that would correspond to the command. This is useful in troubleshooting. However, the string includes a function to get the token, and that function references the `vault` client as opposed to the `bao` client. Clearly, that doesn't work.

**To Reproduce**

Run `bao status -output-curl-string`

observe the following output:

`curl -H "X-Vault-Request: true" -H "X-Vault-Token: $(vault print token)" https://127.0.0.1:8200/v1/sys/seal-status`

the `$(vault print token)` bit is problematic and should be `$(bao print token)`

**Expected behavior**
I expect the `bao` client to depend on `bao` and not `vault`.

**Environment:**
* OpenBao Server Version (retrieve with `bao status`): 2.0.0
* OpenBao CLI Version (retrieve with `bao version`): OpenBao v2.0.0 (700fe3f27ab1f0ec39ce20c36f6d9d97c9fe6ac3), built 2024-07-17T22:05:40Z
* Server Operating System/Architecture: server: linux; workstation: mac

OpenBao server configuration file(s):

```hcl
disable_cache = false

cluster_addr = "<scrubbed>"
api_addr = "<scrubbed>"

ui = true

listener "tcp" {
  address         = "[::]:8200"
  cluster_address = "[::]:8201"
  tls_cert_file = "<scrubbed>"
  tls_key_file = "<scrubbed>"
}


storage "raft" {
  path = "/data/raft"
  node_id = "raft_node_1"
}

max_lease_ttl = "10h"
default_lease_ttl = "10h"
cluster_name = "testcluster"
pid_file = "./pidfile"
raw_storage_endpoint = true
introspection_endpoint = true
disable_sealwrap = true
disable_printable_check = true
enable_response_header_hostname = true
enable_response_header_raft_node_id = true
```

**Additional context**
This fix is trivial and I have a [commit](https://github.com/openbao/openbao/compare/main...Btijmen:openbao:main) in my own fork, but to open a PR I needed to create an issue first.

**Comment by cipherboy** [comment]
Fixed by #511. Thanks @Btijmen!
