### ISSUE TITLE
Plans for AWS and Azure auth/secret engines

### ISSUE THREAD

**Issue by dniasoff** [openbao/openbao#542]
Spent quite a bit of time replacing vault with openbao in our kubernetes pipeline but realised that I couldn't use it because it didn't have the modules to support AWS and Azure which is quite a show stopper.

What are the plans to support the major cloud providers?

**Comment by dniasoff** [comment]
It seems AWS and GCP support is in the pipeline

**Comment by cipherboy** [comment]
@dniasoff Yep, thanks for the reminder! I think soon with the [Dev WG charter](https://lists.lfedge.org/g/OpenBao-TSC/topic/dev_wg_charter/108540148) we'll have the framework to start opening these up as separate repositories.
