### ISSUE TITLE
PKI: ACME is not working with IPv6 in SAN (Vault #28480)

### ISSUE THREAD

**Issue by cipherboy** [openbao/openbao#551]
As reported by @M0NsTeRRR on https://github.com/hashicorp/vault/issues/28480:

> **Describe the bug** The HTTP-01 & challenge does not format properly domain when it's set to the IPv6 address must be enclosed in brackets. https://github.com/hashicorp/vault/blob/main/builtin/logical/pki/acme_challenges.go#L126
> 
> Challenge fail with this error in lego
> 
> ```
> [INFO] [2a0c:b641:2c0:110::21] acme: Trying to solve HTTP-01\n2024/09/23 22:06:14 [INFO] Skipping deactivating of valid auth: https://vault.unicornafk.fr:8200/v1/pki/acme/authorization/2784580b-b852-4fce-8ed3-3ab805c816f9\n2024/09/23 22:06:14 [INFO] Skipping deactivating of valid auth: https://vault.unicornafk.fr:8200/v1/pki/acme/authorization/55e91f06-fb6e-aec0-e303-7769a202817a\n2024/09/23 22:06:14 [INFO] Deactivating auth: https://vault.unicornafk.fr:8200/v1/pki/acme/authorization/7c59f2a2-b0bf-7e70-0d77-e5a50af70a8c\n2024/09/23 22:06:14 [INFO] Unable to deactivate the authorization: https://vault.unicornafk.fr:8200/v1/pki/acme/authorization/7c59f2a2-b0bf-7e70-0d77-e5a50af70a8c\n2024/09/23 22:06:14 Could not obtain certificates:\n\terror: one or more domains had a problem:\n[2a0c:b641:2c0:110::21] acme: error: 400 :: urn:ietf:params:acme:error:incorrectResponse :: Response received didn\'t match the challenge\'s requirements: error validating http-01 challenge 7c59f2a2-b0bf-7e70-0d77-e5a50af70a8c-http-01: http-01: failed to fetch path http://2a0c:b641:2c0:110::21/.well-known/acme-challenge/JJqdDgTEKYUUksBUhT9hWeo9eVkM: Get "http://2a0c:b641:2c0:110::21/.well-known/acme-challenge/JJqdDgTEKYUUksBUhT9hWeo9eVkM": dial tcp: lookup 2a0c:b641:2c0:110:: no such host; this may occur if the validation target was misconfigured: check that challenge responses are available at the required locations and retry.\n
> ```
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Configure pki with ACME
> 
>     2. Try to get a certificate through vault ACME with lego (for example) with an IPv6 in the SAN.
> 
> 
> **Expected behavior** Vault should connect properly to my IPv6 webserver
> 
> **Environment:**
> 
>     * Vault Server Version (retrieve with `vault status`): 1.17.5
> 
>     * Vault CLI Version (retrieve with `vault version`):
> 
>     * Server Operating System/Architecture: Ubuntu 22.04 Server LTS

---

This does appear like a valid bug. I suspect what will address this is modifying the call site:

https://github.com/openbao/openbao/blob/e6c8d4fd69a06b3e8d8a8a9e88dcc9e122ef176b/builtin/logical/pki/acme_challenge_engine.go#L427-L442

to check for IPv6 and sending the correct hostname as a result. I think the best way to do this is to extend `ACMEIdentifier` to include an `IPv6 = ip.To4() != nil` value:

https://github.com/openbao/openbao/blob/e6c8d4fd69a06b3e8d8a8a9e88dcc9e122ef176b/builtin/logical/pki/acme_authorizations.go#L18-L23

https://github.com/openbao/openbao/blob/e6c8d4fd69a06b3e8d8a8a9e88dcc9e122ef176b/builtin/logical/pki/path_acme_order.go#L963-L968

and that will mean we only have to parse the IP address once. Technically we could fail to do so for existing orders (on ACME server restart) but those should only be valid for a limited time and were already failing. The ACME client should retry them.

**Comment by cipherboy** [comment]
@M0NsTeRRR if you want to take a stab at this, happy to have you, otherwise I'm willing to do this one myself. Let me know! :-)

**Comment by M0NsTeRRR** [comment]
Don't have time for now to fix it, so I let you do it if you got some time :)
