### ISSUE TITLE
Feature Request: Events

### ISSUE THREAD

**Issue by sedadas** [openbao/openbao#553]
**Is your feature request related to a problem? Please describe.**
The feature is not connected to a problem, but it is a useful integration for monitoring, audits and CI/CD.

**Describe the solution you'd like**
A solution, similar to what is offered by Hashicorp in their beta API for [Vault 1.14.x](https://developer.hashicorp.com/vault/docs/v1.14.x/concepts/events) would be ideal. In later versions this is an enterprise feature, but here it is a beta one.

**Describe alternatives you've considered**
N/A

**Explain any additional use-cases**
We use the beta event API for capturing events when a secret is created/updated/deleted and we then create/update/delete the secret on another instance, using custom handling which is not covered by the replication functionality Vault Enterprise offers.
Additionally, this feature allows replication using storage backends that do not support transactional updates.

It may also be used for automatically extracting a secret and running a CI/CD pipeline with the value.

**Additional context**
N/A

**Comment by cipherboy** [comment]
Hello @sedadas -- Events were removed as they were still in beta and being a larger feature, we were unable to support them to completion.

One thing that particularly makes events hard is that they require instrumenting every single piece of OpenBao to be useful. The event subsystem was meant to provide server-indicated events of changes, sometimes changes that were internal to OpenBao and thus required different data structures to work well.

For instance, one suggested use case was the PKI engine and leaf cert expiry. To know the next-expiring leaf certificate however, we'd have to maintain a mapping on issuance/tidy or iterate over all certificates --- plus, this doesn't work with `no_store=true` unless we explicitly maintained an expiration index for those. This would also require instrumenting all third-party plugins... 

IMO, most problems solvable using the Events API are better solved with [careful tuning](https://openbao.org/docs/secrets/pki/considerations/) of the Audit log and letting an external service handle notifications. In most cases, you want a separation of concerns between the actual secrets manager (OpenBao) and the event pub/sub system. This already triggers on all of the conditions you've listed. From here, you can build an external eventing system that doesn't impact the performance of OpenBao. Lastly, Events as implemented in Vault were best-effort without retry, whereas the Audit system guaranteed delivery. 

> Additionally, this feature allows replication using storage backends that do not support transactional updates.

I'm not sure I follow this. Can you explain more? There is already HA support (using Raft in a `ha_storage` clause) for non-HA backends. But how does Events help with transactions? I don't understand why we'd need two different HA mechanisms, or how Events [adds transactions](https://github.com/openbao/openbao/issues/296) to a non-transactional storage

> It may also be used for automatically extracting a secret and running a CI/CD pipeline with the value.

Again, I don't quite understand this. Are you suggesting that if, in a secrets manager, a secret was updated (which, ideally, dynamic secrets would be used so the secret would always be generated fresh for each request...), you'd trigger a CI/CD pipeline to ensure the new secret value... works?

Paths are already public/non-HMAC'd in the audit log so this should be possible to build, today, with Audit subsystem. :-)

My 2c., but I'd like to see better tooling around the Audit log first before we go down this path.

**Comment by sedadas** [comment]
Thank you for the fast response.

> I'm not sure I follow this. Can you explain more? There is already HA support (using Raft in a ha_storage clause) for non-HA backends. But how does Events help with transactions? I don't understand why we'd need two different HA mechanisms, or how Events https://github.com/openbao/openbao/issues/296 to a non-transactional storage

Perhaps a use case would be good. We have a Vault installation on-premises and a Vault installation in the cloud.
They cannot communicate with each other.
We are using a custom-written tool that captures certain events from the on-premise installation and acts upon the changes - e.g., if a secret is modified and its name/path/version/whatever matches some predefined conditions, perform the same action on the cloud instance. This is not doable with replication.

> It may also be used for automatically extracting a secret and running a CI/CD pipeline with the value.

A use-case would be this: you have a mission-critical system that must be deployable even when Vault is down (for example, the system where Vault runs), but you want to manage its secrets in Vault. Using events, you can have a CI/CD pipeline that captures them, gets the new values, encrypts them (using `ansible-vault` or `helm-secrets` or pgp or whatever) and commits them to a repository. Thus, you have a self-contained repository with all the secrets inside, but also the convenience of using Vault for managing them (automatic rotation and so on).

**Comment by cipherboy** [comment]
Yeah, I think especially in the former use case, you want event delivery guarantees and hence want to be using the audit log. In the latter use case, as long as the old secret was usable, you wouldn't _necessarily_ run into problems... But you'd probably at least want consistency between secrets (if you updated secrets A, B, and C, and event B got dropped somehow, that'd maybe be bad if C was related to B?)... 

So I'd definitely suggest using the Audit log for both cases. :-) 

If there's something here to make Audit log _better_, I'm all for that. There were a lot of problems with the new audit log framework HashiCorp rolled out (1.15+?) --- but I think we could make the version we have better in certain ways. Perhaps supporting external audit logging plugins for one.

**Comment by cipherboy** [comment]
Per today's [community call](https://lf-edge.atlassian.net/wiki/spaces/OP/pages/15211863/OpenBao+Meetings), I'm going to go ahead and close this. We're happy to reconsider later, but for now, based on these use cases, we think the audit system will be sufficient and more ideal. However, there's definitely a bunch of necessary improvements to audit subsystem. :-)

**Comment by Agalin** [comment]
With this year's roadmap (#1974) including Vault Secrets Operator release, maybe it's time to reconsider? Since version 0.8.0 it uses Events API for instant secret sync to K8s after secret is changed in Vault.

Of course that assumes OpenBao version doesn't add support for doing such things over Audit API.
