### ISSUE TITLE
Support for podman testcluster

### ISSUE THREAD

**Issue by v0nNemizez** [openbao/openbao#571]
**Is your feature request related to a problem? Please describe.**
Support for podman in sdk/helpers/testcluster

**Describe the solution you'd like**
Out-of-the-box support for a testcluster running in podman

**Describe alternatives you've considered**
Installing docker is not a option because of license cost

**Explain any additional use-cases**
Docker is no longer the the only desktop container manager used for testing and running applications. For example our company is using podman because of license costs. This considerd, we shoud give devs a choice :) 

**Additional context**
I can have a go at this! :)

**Comment by cipherboy** [comment]
\o hey @v0nNemizez -- I already use `podman` rather extensively, including on Ubuntu and Fedora.

My setup looks something like:

```
$ systemctl --user enable --now podman.socket
$ export DOCKER_HOST=unix:///run/user/1000/podman/podman.sock
```

and everything else just works, thanks to the fine folks over in the Podman team and their eye for compatibility. 

<details>
<summary> The socket's unit file looks like: </summary>


```
# /usr/lib/systemd/user/podman.socket
[Unit]
Description=Podman API Socket
Documentation=man:podman-system-service(1)

[Socket]
ListenStream=%t/podman/podman.sock
SocketMode=0660

[Install]
WantedBy=sockets.target
```

and the service file looks like:

```
# /usr/lib/systemd/user/podman.service
[Unit]
Description=Podman API Service
Requires=podman.socket
After=podman.socket
Documentation=man:podman-system-service(1)
StartLimitIntervalSec=0

[Service]
Delegate=true
Type=exec
KillMode=process
Environment=LOGGING="--log-level=info"
ExecStart=/usr/bin/podman $LOGGING system service

[Install]
WantedBy=default.target

# /usr/lib/systemd/user/service.d/10-timeout-abort.conf
# This file is part of the systemd package.
# See https://fedoraproject.org/wiki/Changes/Shorter_Shutdown_Timer.
#
# To facilitate debugging when a service fails to stop cleanly,
# TimeoutStopFailureMode=abort is set to "crash" services that fail to stop in
# the time allotted. This will cause the service to be terminated with SIGABRT
# and a coredump to be generated.
#
# To undo this configuration change, create a mask file:
#   sudo mkdir -p /etc/systemd/user/service.d
#   sudo ln -sv /dev/null /etc/systemd/user/service.d/10-timeout-abort.conf

[Service]
TimeoutStopFailureMode=abort
```

</details>

Let me know if that doesn't work for you --- I suspect the paths might be different if you're coming from MacOS, but otherwise most Linux distributions (with new enough podman and using systemd) should ship the service files.

**Comment by cipherboy** [comment]
My understanding is also that while Docker Desktop and their registry have had tighter restrictions, so far their Go API hasn't been problematically licensed. I assume that'll still be the case, but if it isn't, we can revisit replacing them with Podman's bindings when that occurs? My 2c.

**Comment by v0nNemizez** [comment]
yeah that works... i got my things fixed on my end by setting the DOCKER_HOST variable to my podman socket. So we can just close this issue for now :)
