### ISSUE TITLE
tlsConfig.RootCAs.Subjects is deprecated: if s was returned by [SystemCertPool], Subjects will not include the system roots.

### ISSUE THREAD

**Issue by fatima2003** [openbao/openbao#575]
**Describe the bug**
`tlsConfig.RootCAs.Subjects is deprecated: if s was returned by [SystemCertPool], Subjects will not include the system roots.` is a warning in the following files: 

```
(base) fatimaopenbao % grep -r "Subjects()" .

./sdk/helper/certutil/certutil_test.go:                 if len(tlsConfig.ClientCAs.Subjects()) != 1 || bytes.Compare(tlsConfig.ClientCAs.Subjects()[0], pcbut.CAChain[0].Certificate.RawSubject) != 0 {
./sdk/helper/certutil/certutil_test.go:                 if len(tlsConfig.RootCAs.Subjects()) != 1 || bytes.Compare(tlsConfig.RootCAs.Subjects()[0], pcbut.CAChain[0].Certificate.RawSubject) != 0 {
./sdk/helper/certutil/certutil_test.go:                 if len(tlsConfig.ClientCAs.Subjects()) != 1 || bytes.Compare(tlsConfig.ClientCAs.Subjects()[0], pcbut.CAChain[0].Certificate.RawSubject) != 0 {
./sdk/helper/certutil/certutil_test.go:                 if len(tlsConfig.RootCAs.Subjects()) != 1 || bytes.Compare(tlsConfig.RootCAs.Subjects()[0], pcbut.CAChain[0].Certificate.RawSubject) != 0 {
./api/client_test.go:   if len(tlsConfig.RootCAs.Subjects()) == 0 {
./vault/diagnose/tls_verification.go:   rootSubjs := rootPool.Subjects()
```

**Expected behavior**
There should be no warning: 
```
tlsConfig.RootCAs.Subjects is deprecated: if s was returned by [SystemCertPool], Subjects will not include the system roots.deprecated[default](https://pkg.go.dev/golang.org/x/tools/gopls/internal/analysis/deprecated)
func (s *x509.CertPool) Subjects() [][]byte
Subjects returns a list of the DER-encoded subjects of all of the certificates in the pool.

Deprecated: if s was returned by [SystemCertPool], Subjects will not include the system roots.

```
___

This could be a quick fix, for instance in ./api/client_test.go, Simply replace `len(tlsConfig.RootCAs.Subjects()) == 0` With `tlsConfig.RootCAs == nil`             

I am looking for replacements in the other files. Should I open a PR after testing the changes?

**Comment by cipherboy** [comment]
@fatima2003 Hmm... But does `tlsConfig.RootCAs == nil` break if we've done https://github.com/openbao/openbao/pull/574#discussion_r1783377589 ? 

I think more ideally, if we had a leaf certificate, which it seems like we may or may not, we'd do something like:

```go
if err := leaf.Verify(VerifyOptions{RootCerts: certPool}); err != nil { ... panic ... }
```

from https://pkg.go.dev/crypto/x509#Certificate.Verify and https://pkg.go.dev/crypto/x509#VerifyOptions  (this may also require provisioning the expected intermediate(s) if any). 

IMO what really matters (and thus, what should be tested) isn't that some certificate is in some root store -- but that said root store _does_ correctly verify the leaf certificate we want. A root CA may still be in a root store, but if there's more intermediates past a root's [`pathLenConstraint`](https://datatracker.ietf.org/doc/html/rfc5280#section-4.2.1.9) that would fail to verify.

My 2c but I think this would be great to clean up :-)

**Comment by fatima2003** [comment]
@cipherboy hmm, yes the suggestion I gave initially was not that well thought out, I’ll investigate using the leaf certificate verification approach and work on cleaning this up!

**Comment by cipherboy** [comment]
@fatima2003 Do you remember what the status of this issue is? I think it is still there, so perhaps we'll fix it later?

**Comment by fatima2003** [comment]
Hmm, I was thinking about getting round to this but never got the opportunity, I will try to look through it tonight and see if I can push a fix soon. If not then perhaps we could leave it on the back burner to fix later :)
