### ISSUE TITLE
incomplete non-voting Raft member implementation

### ISSUE THREAD

**Issue by zarganum** [openbao/openbao#578]
**Is your feature request related to a problem? Please describe.**
The non-voting cluster member is used for native Raft replication (originally Enterprise-only).

**Describe the solution you'd like**
[Re-enable](https://github.com/openbao/openbao/blob/main/physical/raft/raft.go#L997) the `non_voter` option.

**Describe alternatives you've considered**
The `retry_join_as_non_voter` option is available but impacts only cluster join.

**Additional context**
The `retry_join_as_non_voter` is marked Enterprise-only in parent product, but still ported here without problems.
However the accompanying `non_voter` option is [explicitly disabled](https://github.com/openbao/openbao/blob/main/physical/raft/raft.go#L997). How so?

**Comment by cipherboy** [comment]
\o hey @zarganum! If you're interested in contributing this, I'd definitely be interested in reviewing it.

This feature was only in Vault Enterprise so not part of the Vault Community edition pre-fork so we never had an implementation for it. :-) I'm not quite sure how large of a feature this is, but if you think its small enough, feel free to file a PR for it, else if you think its larger, a RFC would be appreciated!

**Comment by zarganum** [comment]
... and if you'd ask me how I've got here: because I broke my cluster badly and start investigating different offline recovery mechanisms that will work when online API fails. Fortunately that was an experimental deployment and I've found [enough info](https://developer.hashicorp.com/vault/tutorials/monitoring/inspect-data-boltdb) about auto-recovery mechanism. What authors did not share is that `latest_config` simply contains a [protobuf version](https://github.com/openbao/openbao/blob/main/physical/raft/types.proto#L39) of `peers.json`.

**Comment by cipherboy** [comment]
\o hello @zarganum:

> Before further investments, may I know if there are legal limitations on re-implementing (or simply porting) the original enterprise features to the OpenBao public fork?

Clean room implementations without looking at upstream's code are the standard here. This is mentioned in the [`CONTRIBUTING.md`](https://github.com/openbao/openbao/blob/main/CONTRIBUTING.md#source-available-license-policy) file:

> This policy prohibits the utilization or copy from any source that is protected by a source-available license agreement including Business Source License 1.1. This specifically includes all source repository members under the Hashicorp GitHub organization. It is the intention of this policy that when developing for feature parity, bug fixes, CVEs, etc. in comparison to Hashicorp Vault that a clean room methodology be used and all deliverables made original.

What makes this entertaining is that the [MPL-licensed Raft library](https://pkg.go.dev/github.com/hashicorp/raft#Raft.AddNonvoter) supports it, so I agree; it should be fairly little work to go add.

But, I'd be careful to stay away from HashiCorp code. If you feel you've seen too much of it already, it may be best to leave this to someone else and find something else to work on. Jan really wants Raft auto-snapshotting, which is in a similar layer of code. :-) 

---

That said, there _must_ be some change to the Raft core besides just to the CLI, because the linked line in your first comment was original from the fork: 

https://github.com/openbao/openbao/blame/d06a3f7b64ca0e14f6fcad6b73028a24506dda11/physical/raft/raft.go#L998

We merely changed Vault Enterprise -> OpenBao.

**Comment by zarganum** [comment]
okay, so auto-snapshotting (of either voter or non-voter node) sounds nice, especially when it comes with seamless S3 object storage compatibility; I cannot say I dig very much into the original code, I'm just curious about Raft native things to work without limitations

**Comment by zarganum** [comment]
and BTW my current intent is to deliver some anti-cloud (yet cloud-assisted) patterns to my customers; so hopefully I will soon investigate more use cases with good old AD, Kerberos and P.A.M niche where OpenBao is a perfect fit for. My customers love to keep their stuff on-prem.

**Comment by cipherboy** [comment]
Ahh, I was a former intern at Red Hat working on Kerberos a long time ago. All for more improvements in that area :-) We also have LDAP engine which would be great to have better testing with AD. 

Check out #569 for some details on auto-snapshotting, but perhaps @JanMa is willing to file an issue with some more details. :-)

**Comment by zarganum** [comment]
> We also have LDAP engine which would be great to have better testing with AD.

what is that, LDAP like a part of testing framework or LDAP forming some OpenBao feature?
LDAP with SASL GSSAPI drove me crazy recently but I won... however it was Python, not Go:)

**Comment by cipherboy** [comment]
See https://openbao.org/docs/auth/ldap/ -- it should also let you authenticate with AD via LDAP instead of Kerberos.

**Comment by zarganum** [comment]
> it should also let you authenticate with AD via LDAP instead of Kerberos

Well, in my code I am burning any LDAP simple binds to the grounds:) It requires TLS, it requires plain password... TLS requires CA trust, plain password requires storing in reversible form... Honestly I just can't see it anymore after so many years of using. But people would always use it despite security because it is simple.

BTW SASL GSSAPI does not require TLS, it negotiates payload encryption up to AES256 even without STARTTLS, right over 389.

**Comment by cipherboy** [comment]
Yes, the benefits of GSSAPI are apparently in a MIT kerb world with C bindings to libgssapi. But Go uses a pure Go reimplementation and I don't believe we have any avenue to support TLS integration with GSSAPI, much less channel bindings which would make that rather useful.

As much as it pains me to say it, as I like the strong PQC properties of symmetric crypto and the work the MIT community has done with SPAKE for strong 2FA, PKI has rather won these days.

**Comment by zarganum** [comment]
> What makes this entertaining is that the [MPL-licensed Raft library](https://pkg.go.dev/github.com/hashicorp/raft#Raft.AddNonvoter) supports it, so I agree; it should be fairly little work to go add.

so let me summarize our topic: 
1) from #569, core features, item 4: horizontal scalability is a priority. The non-voting mech is not a direct part but a highly related one to the read-only replication. 
2) the non-voting ability of Raft node is MPL-licensed, separately.
3) the `retry_join_as_non_voter` is already in the OpenBao.
4) the non-voting config enablement is rather a deletion of code than addition.
5) the API/CLI of non-voter can be delegated to someone else.

After unlocking the non-voter config, hopefully a new Disaster Recovery Guide can be made, more complete. 
Showing for example how to re-create a full cluster from just a single replica, how to promote and demote nodes using offline techniques.

agree?

**Comment by zarganum** [comment]
> As much as it pains me to say it, as I like the strong PQC properties of symmetric crypto and the work the MIT community has done with SPAKE for strong 2FA, PKI has rather won these days.

Agree that PKI is an absolute winner everywhere except "native" MS AD environment that appears to rely on SASL/GSSAPI for decades and will never stop until its death. And it pains me to say that 2FA is probably lost completely there because the entry level is just too high to code in C language, this just does not work. So in my current initiatives I take the best from both worlds bridging the old school MS Kerberos with the new MFA, PAM, etc, delivered using modern dev stacks.

And it is a common myth that cloud infrastructure is a total cost saver. No, this is applicable for larger enterprises, 
my sales dept totally confirms this:)

**Comment by JanMa** [comment]
I started to take a look at this yesterday evening and it looks straightforward to implement. I'll open a PR for this in the next days

**Comment by cipherboy** [comment]
@zarganum Are you still interested in doing auto-snapshotting of Raft storage by any chance? :-)

**Comment by zarganum** [comment]
@cipherboy I cannot give commitments but let's first define the feature:)
Do you have any previous discussions on its scope and use cases?
Will it be primarily used by single-node deployments (rather than clustered)?
Should the snapshot be triggered internally (by configured schedule) or externally (e.g. by SIGUSR1)? Signals would limit to POSIX only (not Windows compatible).
Should the post-snapshot command be run to sync the fresh snapshot to some external storage? If yes, should the bao process track its exit status and abort execution after specified timeout reached?
