### ISSUE TITLE
storage/postgresql: Automatically add tables when selecting postgresql as secret storage (vault#28545)

### ISSUE THREAD

**Issue by cipherboy** [openbao/openbao#612]
@FunkForever writes on https://github.com/hashicorp/vault/issues/28545: 

> **Is your feature request related to a problem? Please describe.**

According to current documentation (https://github.com/hashicorp/vault/blob/main/website/content/docs/configuration/storage/postgresql.mdx vault cannot create tables automatically. I use helm chart from bank vault to deploy vault (https://github.com/bank-vaults/vault-helm-chart). At the moment I am unfolding the tables manually. When deploying manually, the first installation always fails, because vault initially creates roles, users and a vault database in PostgreSQL, and then creates tables on top of that. Pre-installation in PostgreSQL is difficult because user credentials created before helm deployment will have different passwords and the application will not be able to get into the database (to create tables, the vault_owner_user user is used, which is automatically created when helm is deployed, and the password is put in secrets).
> 
> **Describe the solution you'd like** Automatically add tables (vault_kv_store, vault_ha_locks) and function (vault_kv_put) when selecting postgresql as secret storage.

---

This makes sense and should be fairly easy to add: a new parameter (perhaps `skip_table_creation=false`) could be added to the configuration. When not skipping, we could detect that [tables do not exist](https://github.com/openbao/openbao/blob/main/physical/postgresql/postgresql.go#L197) and then attempt to create them.

**Comment by FunkForever** [comment]
Great idea! I fully support it.

**Comment by cipherboy** [comment]
@FunkForever Cool! Are you interested in implementing it? Happy to review a PR if so. :-)

If you build OpenBao from `main` currently, you can also try out our new support for transactions with the Postgres backend; see #608.

**Comment by FunkForever** [comment]
Thanks, but I can't help you with the implementation. I am a devops engineer and rarely do development in practice.

**Comment by cipherboy** [comment]
\o hey @FunkForever -- this was in our v2.1.0 release that was released on Friday :-) Let us know if you end up using it or run into any problems!
