### ISSUE TITLE
Fork: Update Vault references within the UI

### ISSUE THREAD

**Issue by cipherboy** [openbao/openbao#74]
The UI utilizes both the Vault name, but also logo and other branding features. We may want a new color scheme, a replacement logo, and name changes in several locations prior to release.

**Comment by cipherboy** [comment]
Synicng some discussion from Matrix earlier:

To remove HashiCorp branding, we ~will need to fork https://github.com/hashicorp/design-system~ have forked https://github.com/openbao/design-system -- this is dep'd from https://github.com/openbao/openbao/blob/main/ui/package.json#L63 -> https://www.npmjs.com/package/@hashicorp/flight-icons -> https://github.com/hashicorp/design-system/tree/main/packages/ember-flight-icons

We may need to republish this to NPM and/or use a [local include](https://stackoverflow.com/questions/15806241/how-to-specify-local-modules-as-npm-package-dependencies) instead if we want to avoid that (probably preferable).

see e.g. packages/flight-icons/svg-original/hashicorp-24.svg or packages/flight-icons/svg/vault-24.svg

**Comment by rhuddleston** [comment]
Random question but since the design-system repo is still MPL 2.0 do we really need to fork/maintain all of that? Can we instead change refernces in the UI code a few places with new icons where they are hashicorp specific or is it more complex than that?

**Comment by cipherboy** [comment]
@rhuddleston IIRC, the issue is the design repo itself has HashiCorp logos &c that are used by OpenBao's UI. So without forking it, our only option would be to ask upstream to make those logos pluggable, which they're unlikely to accept as they have no need for it.

**Comment by rhuddleston** [comment]
I guess was hoping we could change `hashicorp` and `vault-logo` references in ui/lib/core/icon-mappings.js to something else instead of having to fork that project? Though I'm not sure how that mappings file is even used.

Digging a but more it seems we can change ui/app/templates/vault.hbs `<Icon @name="hashicorp"` to change the footer I think

ui/app/templates/vault/cluster/auth.hbs and ui/app/templates/vault/error.hbs both reference `Icon @name="vault"` and could be changed to reference other icons but there are probably more places

**Comment by cipherboy** [comment]
Go for it if you think it's doable! I will confess my frontend experience is quite minimal and limited to carefully supervised attempts. :D I have a little more familiarity with React, but even that isn't extensive enough to feel confident taking this on myself.

**Comment by cipherboy** [comment]
This looks to be complete! Thanks @bozzo and @jenrik and whomever else I might've forgotten to thank!
