### ISSUE TITLE
Transit: Add public key format

### ISSUE THREAD

**Issue by cipherboy** [openbao/openbao#86]
Per @SchulzeStTSI on https://github.com/hashicorp/vault/issues/25141:

> **Describe the bug** When retrieving the public key of an ed25519 key pair from the transit API the key is formatted in a strange encoding. After checking it, i found out that the key is simply a base64 encoding of ed25519.PublicKey which is the internal go type representation.
> 
> **To Reproduce** Generate ed25519 keypair and use the private one to extract the public:
> 
> ```
> p := key.Public().(ed25519.PublicKey)
> b := base64.StdEncoding.EncodeToString(p)
> ```
> 
> Output is an base64 string which is not a PEM or anything else "usable" by openssl. Something like this: DixHOIHXtDW0l6DHE2qGCRCfC/XjS5CHxHS+sEUICH0=
> 
> **Expected behavior** Convert the key into a PEM format/standard encoding that it matches with the other key pair types in format (they use all pub keys in PEM format) to have this format:
> 
> -----BEGIN PUBLIC KEY----- MCowBQYDK2VwAyEA8eIBpK/74foJBEzRn2kCImhWyVnOcqV5aX1L8DSHyxA= -----END PUBLIC KEY-----
> 
> This is then readable by openssl.
> 
> ```
> bytes, err := x509.MarshalPKIXPublicKey(key.PublicKey())
> 
> if err != nil {
> return nil, err
> }
> 
> pemBlock := &pem.Block{
> Type:  "PUBLIC KEY",
> Bytes: bytes,
> }
> 
> pubkey_bytes := pem.EncodeToMemory(pemBlock)
> ```

---

Since changing the key format now will likely break compatibility, we should probably add a new `format` parameter to the `transit/export/:type/:key` API. This would allow callers to specify the format (defaulting perhaps to `native`). 

However, if the OpenSSL application is modifiable, I believe the `EVP_PKEY_new_raw_private_key` and `EVP_PKEY_new_raw_public_key` [API calls](https://www.openssl.org/docs/man1.1.1/man3/EVP_PKEY_new_raw_private_key.html) are useful for parsing Vault keys. Not sure if there's a comparable OpenSSL 3.0 API though.

**Comment by naphelps** [comment]
Migration guide: https://www.openssl.org/docs/man3.1/man7/migration_guide.html

The OpenSSL 1.1.1 apis went EOL back in November. We should probably work on migrating these to the current 3.2 version.

**Comment by cipherboy** [comment]
@naphelps Note that we do not use OpenSSL; this was advice I was giving to OP on how they could call a different function for Ed25519 keys (in their app) to support the format Go uses: https://pkg.go.dev/crypto/ed25519

The public key, as discussed in [RFC 8032](https://www.rfc-editor.org/rfc/rfc8032.html#section-5.1.5) is 32 bytes. It is not a PEM blob.

It looks like these functions are still present in 3.1 though: https://www.openssl.org/docs/man3.1/man3/EVP_PKEY_get_raw_public_key.html

I'd still probably implement both formats for all keys for consistency.
